"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any, MutableSequence
from temporalio.api.common.v1.message_pb2 import Payload

class VisitorFunctions(abc.ABC):
    """Set of functions which can be called by the visitor.
    Allows handling payloads as a sequence.
    """
    @abc.abstractmethod
    async def visit_payload(self, payload: Payload) -> None:
        """Called when encountering a single payload."""
        ...
    
    @abc.abstractmethod
    async def visit_payloads(self, payloads: MutableSequence[Payload]) -> None:
        """Called when encountering multiple payloads together."""
        ...
    


class PayloadVisitor:
    """A visitor for payloads.
    Applies a function to every payload in a tree of messages.
    """
    def __init__(self, *, skip_search_attributes: bool = ..., skip_headers: bool = ...) -> None:
        """Creates a new payload visitor."""
        ...
    
    async def visit(self, fs: VisitorFunctions, root: Any) -> None:
        """Visits the given root message with the given function."""
        ...
    


