"""
This type stub file was generated by pyright.
"""

import google.protobuf.empty_pb2
import temporalio.api.cloud.cloudservice.v1
import temporalio.api.operatorservice.v1
import temporalio.api.testservice.v1
import temporalio.api.workflowservice.v1
import temporalio.bridge.proto.health.v1
from datetime import timedelta
from typing import Mapping, Optional, TYPE_CHECKING, Union
from temporalio.service import ServiceClient

"""Generated RPC calls for Temporal services."""
if TYPE_CHECKING:
    ...
class WorkflowService:
    """RPC calls for the WorkflowService."""
    def __init__(self, client: ServiceClient) -> None:
        """Initialize service with the provided ServiceClient."""
        ...
    
    async def count_workflow_executions(self, req: temporalio.api.workflowservice.v1.CountWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.CountWorkflowExecutionsResponse:
        """Invokes the WorkflowService.count_workflow_executions rpc method."""
        ...
    
    async def create_schedule(self, req: temporalio.api.workflowservice.v1.CreateScheduleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.CreateScheduleResponse:
        """Invokes the WorkflowService.create_schedule rpc method."""
        ...
    
    async def create_workflow_rule(self, req: temporalio.api.workflowservice.v1.CreateWorkflowRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.CreateWorkflowRuleResponse:
        """Invokes the WorkflowService.create_workflow_rule rpc method."""
        ...
    
    async def delete_schedule(self, req: temporalio.api.workflowservice.v1.DeleteScheduleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeleteScheduleResponse:
        """Invokes the WorkflowService.delete_schedule rpc method."""
        ...
    
    async def delete_worker_deployment(self, req: temporalio.api.workflowservice.v1.DeleteWorkerDeploymentRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeleteWorkerDeploymentResponse:
        """Invokes the WorkflowService.delete_worker_deployment rpc method."""
        ...
    
    async def delete_worker_deployment_version(self, req: temporalio.api.workflowservice.v1.DeleteWorkerDeploymentVersionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeleteWorkerDeploymentVersionResponse:
        """Invokes the WorkflowService.delete_worker_deployment_version rpc method."""
        ...
    
    async def delete_workflow_execution(self, req: temporalio.api.workflowservice.v1.DeleteWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeleteWorkflowExecutionResponse:
        """Invokes the WorkflowService.delete_workflow_execution rpc method."""
        ...
    
    async def delete_workflow_rule(self, req: temporalio.api.workflowservice.v1.DeleteWorkflowRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeleteWorkflowRuleResponse:
        """Invokes the WorkflowService.delete_workflow_rule rpc method."""
        ...
    
    async def deprecate_namespace(self, req: temporalio.api.workflowservice.v1.DeprecateNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DeprecateNamespaceResponse:
        """Invokes the WorkflowService.deprecate_namespace rpc method."""
        ...
    
    async def describe_batch_operation(self, req: temporalio.api.workflowservice.v1.DescribeBatchOperationRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeBatchOperationResponse:
        """Invokes the WorkflowService.describe_batch_operation rpc method."""
        ...
    
    async def describe_deployment(self, req: temporalio.api.workflowservice.v1.DescribeDeploymentRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeDeploymentResponse:
        """Invokes the WorkflowService.describe_deployment rpc method."""
        ...
    
    async def describe_namespace(self, req: temporalio.api.workflowservice.v1.DescribeNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeNamespaceResponse:
        """Invokes the WorkflowService.describe_namespace rpc method."""
        ...
    
    async def describe_schedule(self, req: temporalio.api.workflowservice.v1.DescribeScheduleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeScheduleResponse:
        """Invokes the WorkflowService.describe_schedule rpc method."""
        ...
    
    async def describe_task_queue(self, req: temporalio.api.workflowservice.v1.DescribeTaskQueueRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeTaskQueueResponse:
        """Invokes the WorkflowService.describe_task_queue rpc method."""
        ...
    
    async def describe_worker(self, req: temporalio.api.workflowservice.v1.DescribeWorkerRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeWorkerResponse:
        """Invokes the WorkflowService.describe_worker rpc method."""
        ...
    
    async def describe_worker_deployment(self, req: temporalio.api.workflowservice.v1.DescribeWorkerDeploymentRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeWorkerDeploymentResponse:
        """Invokes the WorkflowService.describe_worker_deployment rpc method."""
        ...
    
    async def describe_worker_deployment_version(self, req: temporalio.api.workflowservice.v1.DescribeWorkerDeploymentVersionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeWorkerDeploymentVersionResponse:
        """Invokes the WorkflowService.describe_worker_deployment_version rpc method."""
        ...
    
    async def describe_workflow_execution(self, req: temporalio.api.workflowservice.v1.DescribeWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeWorkflowExecutionResponse:
        """Invokes the WorkflowService.describe_workflow_execution rpc method."""
        ...
    
    async def describe_workflow_rule(self, req: temporalio.api.workflowservice.v1.DescribeWorkflowRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.DescribeWorkflowRuleResponse:
        """Invokes the WorkflowService.describe_workflow_rule rpc method."""
        ...
    
    async def execute_multi_operation(self, req: temporalio.api.workflowservice.v1.ExecuteMultiOperationRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ExecuteMultiOperationResponse:
        """Invokes the WorkflowService.execute_multi_operation rpc method."""
        ...
    
    async def fetch_worker_config(self, req: temporalio.api.workflowservice.v1.FetchWorkerConfigRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.FetchWorkerConfigResponse:
        """Invokes the WorkflowService.fetch_worker_config rpc method."""
        ...
    
    async def get_cluster_info(self, req: temporalio.api.workflowservice.v1.GetClusterInfoRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetClusterInfoResponse:
        """Invokes the WorkflowService.get_cluster_info rpc method."""
        ...
    
    async def get_current_deployment(self, req: temporalio.api.workflowservice.v1.GetCurrentDeploymentRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetCurrentDeploymentResponse:
        """Invokes the WorkflowService.get_current_deployment rpc method."""
        ...
    
    async def get_deployment_reachability(self, req: temporalio.api.workflowservice.v1.GetDeploymentReachabilityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetDeploymentReachabilityResponse:
        """Invokes the WorkflowService.get_deployment_reachability rpc method."""
        ...
    
    async def get_search_attributes(self, req: temporalio.api.workflowservice.v1.GetSearchAttributesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetSearchAttributesResponse:
        """Invokes the WorkflowService.get_search_attributes rpc method."""
        ...
    
    async def get_system_info(self, req: temporalio.api.workflowservice.v1.GetSystemInfoRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetSystemInfoResponse:
        """Invokes the WorkflowService.get_system_info rpc method."""
        ...
    
    async def get_worker_build_id_compatibility(self, req: temporalio.api.workflowservice.v1.GetWorkerBuildIdCompatibilityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetWorkerBuildIdCompatibilityResponse:
        """Invokes the WorkflowService.get_worker_build_id_compatibility rpc method."""
        ...
    
    async def get_worker_task_reachability(self, req: temporalio.api.workflowservice.v1.GetWorkerTaskReachabilityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetWorkerTaskReachabilityResponse:
        """Invokes the WorkflowService.get_worker_task_reachability rpc method."""
        ...
    
    async def get_worker_versioning_rules(self, req: temporalio.api.workflowservice.v1.GetWorkerVersioningRulesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetWorkerVersioningRulesResponse:
        """Invokes the WorkflowService.get_worker_versioning_rules rpc method."""
        ...
    
    async def get_workflow_execution_history(self, req: temporalio.api.workflowservice.v1.GetWorkflowExecutionHistoryRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetWorkflowExecutionHistoryResponse:
        """Invokes the WorkflowService.get_workflow_execution_history rpc method."""
        ...
    
    async def get_workflow_execution_history_reverse(self, req: temporalio.api.workflowservice.v1.GetWorkflowExecutionHistoryReverseRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.GetWorkflowExecutionHistoryReverseResponse:
        """Invokes the WorkflowService.get_workflow_execution_history_reverse rpc method."""
        ...
    
    async def list_archived_workflow_executions(self, req: temporalio.api.workflowservice.v1.ListArchivedWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListArchivedWorkflowExecutionsResponse:
        """Invokes the WorkflowService.list_archived_workflow_executions rpc method."""
        ...
    
    async def list_batch_operations(self, req: temporalio.api.workflowservice.v1.ListBatchOperationsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListBatchOperationsResponse:
        """Invokes the WorkflowService.list_batch_operations rpc method."""
        ...
    
    async def list_closed_workflow_executions(self, req: temporalio.api.workflowservice.v1.ListClosedWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListClosedWorkflowExecutionsResponse:
        """Invokes the WorkflowService.list_closed_workflow_executions rpc method."""
        ...
    
    async def list_deployments(self, req: temporalio.api.workflowservice.v1.ListDeploymentsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListDeploymentsResponse:
        """Invokes the WorkflowService.list_deployments rpc method."""
        ...
    
    async def list_namespaces(self, req: temporalio.api.workflowservice.v1.ListNamespacesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListNamespacesResponse:
        """Invokes the WorkflowService.list_namespaces rpc method."""
        ...
    
    async def list_open_workflow_executions(self, req: temporalio.api.workflowservice.v1.ListOpenWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListOpenWorkflowExecutionsResponse:
        """Invokes the WorkflowService.list_open_workflow_executions rpc method."""
        ...
    
    async def list_schedule_matching_times(self, req: temporalio.api.workflowservice.v1.ListScheduleMatchingTimesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListScheduleMatchingTimesResponse:
        """Invokes the WorkflowService.list_schedule_matching_times rpc method."""
        ...
    
    async def list_schedules(self, req: temporalio.api.workflowservice.v1.ListSchedulesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListSchedulesResponse:
        """Invokes the WorkflowService.list_schedules rpc method."""
        ...
    
    async def list_task_queue_partitions(self, req: temporalio.api.workflowservice.v1.ListTaskQueuePartitionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListTaskQueuePartitionsResponse:
        """Invokes the WorkflowService.list_task_queue_partitions rpc method."""
        ...
    
    async def list_worker_deployments(self, req: temporalio.api.workflowservice.v1.ListWorkerDeploymentsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListWorkerDeploymentsResponse:
        """Invokes the WorkflowService.list_worker_deployments rpc method."""
        ...
    
    async def list_workers(self, req: temporalio.api.workflowservice.v1.ListWorkersRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListWorkersResponse:
        """Invokes the WorkflowService.list_workers rpc method."""
        ...
    
    async def list_workflow_executions(self, req: temporalio.api.workflowservice.v1.ListWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListWorkflowExecutionsResponse:
        """Invokes the WorkflowService.list_workflow_executions rpc method."""
        ...
    
    async def list_workflow_rules(self, req: temporalio.api.workflowservice.v1.ListWorkflowRulesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ListWorkflowRulesResponse:
        """Invokes the WorkflowService.list_workflow_rules rpc method."""
        ...
    
    async def patch_schedule(self, req: temporalio.api.workflowservice.v1.PatchScheduleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PatchScheduleResponse:
        """Invokes the WorkflowService.patch_schedule rpc method."""
        ...
    
    async def pause_activity(self, req: temporalio.api.workflowservice.v1.PauseActivityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PauseActivityResponse:
        """Invokes the WorkflowService.pause_activity rpc method."""
        ...
    
    async def poll_activity_task_queue(self, req: temporalio.api.workflowservice.v1.PollActivityTaskQueueRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PollActivityTaskQueueResponse:
        """Invokes the WorkflowService.poll_activity_task_queue rpc method."""
        ...
    
    async def poll_nexus_task_queue(self, req: temporalio.api.workflowservice.v1.PollNexusTaskQueueRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PollNexusTaskQueueResponse:
        """Invokes the WorkflowService.poll_nexus_task_queue rpc method."""
        ...
    
    async def poll_workflow_execution_update(self, req: temporalio.api.workflowservice.v1.PollWorkflowExecutionUpdateRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PollWorkflowExecutionUpdateResponse:
        """Invokes the WorkflowService.poll_workflow_execution_update rpc method."""
        ...
    
    async def poll_workflow_task_queue(self, req: temporalio.api.workflowservice.v1.PollWorkflowTaskQueueRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.PollWorkflowTaskQueueResponse:
        """Invokes the WorkflowService.poll_workflow_task_queue rpc method."""
        ...
    
    async def query_workflow(self, req: temporalio.api.workflowservice.v1.QueryWorkflowRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.QueryWorkflowResponse:
        """Invokes the WorkflowService.query_workflow rpc method."""
        ...
    
    async def record_activity_task_heartbeat(self, req: temporalio.api.workflowservice.v1.RecordActivityTaskHeartbeatRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RecordActivityTaskHeartbeatResponse:
        """Invokes the WorkflowService.record_activity_task_heartbeat rpc method."""
        ...
    
    async def record_activity_task_heartbeat_by_id(self, req: temporalio.api.workflowservice.v1.RecordActivityTaskHeartbeatByIdRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RecordActivityTaskHeartbeatByIdResponse:
        """Invokes the WorkflowService.record_activity_task_heartbeat_by_id rpc method."""
        ...
    
    async def record_worker_heartbeat(self, req: temporalio.api.workflowservice.v1.RecordWorkerHeartbeatRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RecordWorkerHeartbeatResponse:
        """Invokes the WorkflowService.record_worker_heartbeat rpc method."""
        ...
    
    async def register_namespace(self, req: temporalio.api.workflowservice.v1.RegisterNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RegisterNamespaceResponse:
        """Invokes the WorkflowService.register_namespace rpc method."""
        ...
    
    async def request_cancel_workflow_execution(self, req: temporalio.api.workflowservice.v1.RequestCancelWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RequestCancelWorkflowExecutionResponse:
        """Invokes the WorkflowService.request_cancel_workflow_execution rpc method."""
        ...
    
    async def reset_activity(self, req: temporalio.api.workflowservice.v1.ResetActivityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ResetActivityResponse:
        """Invokes the WorkflowService.reset_activity rpc method."""
        ...
    
    async def reset_sticky_task_queue(self, req: temporalio.api.workflowservice.v1.ResetStickyTaskQueueRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ResetStickyTaskQueueResponse:
        """Invokes the WorkflowService.reset_sticky_task_queue rpc method."""
        ...
    
    async def reset_workflow_execution(self, req: temporalio.api.workflowservice.v1.ResetWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ResetWorkflowExecutionResponse:
        """Invokes the WorkflowService.reset_workflow_execution rpc method."""
        ...
    
    async def respond_activity_task_canceled(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskCanceledRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskCanceledResponse:
        """Invokes the WorkflowService.respond_activity_task_canceled rpc method."""
        ...
    
    async def respond_activity_task_canceled_by_id(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskCanceledByIdRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskCanceledByIdResponse:
        """Invokes the WorkflowService.respond_activity_task_canceled_by_id rpc method."""
        ...
    
    async def respond_activity_task_completed(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskCompletedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskCompletedResponse:
        """Invokes the WorkflowService.respond_activity_task_completed rpc method."""
        ...
    
    async def respond_activity_task_completed_by_id(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskCompletedByIdRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskCompletedByIdResponse:
        """Invokes the WorkflowService.respond_activity_task_completed_by_id rpc method."""
        ...
    
    async def respond_activity_task_failed(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskFailedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskFailedResponse:
        """Invokes the WorkflowService.respond_activity_task_failed rpc method."""
        ...
    
    async def respond_activity_task_failed_by_id(self, req: temporalio.api.workflowservice.v1.RespondActivityTaskFailedByIdRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondActivityTaskFailedByIdResponse:
        """Invokes the WorkflowService.respond_activity_task_failed_by_id rpc method."""
        ...
    
    async def respond_nexus_task_completed(self, req: temporalio.api.workflowservice.v1.RespondNexusTaskCompletedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondNexusTaskCompletedResponse:
        """Invokes the WorkflowService.respond_nexus_task_completed rpc method."""
        ...
    
    async def respond_nexus_task_failed(self, req: temporalio.api.workflowservice.v1.RespondNexusTaskFailedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondNexusTaskFailedResponse:
        """Invokes the WorkflowService.respond_nexus_task_failed rpc method."""
        ...
    
    async def respond_query_task_completed(self, req: temporalio.api.workflowservice.v1.RespondQueryTaskCompletedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondQueryTaskCompletedResponse:
        """Invokes the WorkflowService.respond_query_task_completed rpc method."""
        ...
    
    async def respond_workflow_task_completed(self, req: temporalio.api.workflowservice.v1.RespondWorkflowTaskCompletedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondWorkflowTaskCompletedResponse:
        """Invokes the WorkflowService.respond_workflow_task_completed rpc method."""
        ...
    
    async def respond_workflow_task_failed(self, req: temporalio.api.workflowservice.v1.RespondWorkflowTaskFailedRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.RespondWorkflowTaskFailedResponse:
        """Invokes the WorkflowService.respond_workflow_task_failed rpc method."""
        ...
    
    async def scan_workflow_executions(self, req: temporalio.api.workflowservice.v1.ScanWorkflowExecutionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ScanWorkflowExecutionsResponse:
        """Invokes the WorkflowService.scan_workflow_executions rpc method."""
        ...
    
    async def set_current_deployment(self, req: temporalio.api.workflowservice.v1.SetCurrentDeploymentRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SetCurrentDeploymentResponse:
        """Invokes the WorkflowService.set_current_deployment rpc method."""
        ...
    
    async def set_worker_deployment_current_version(self, req: temporalio.api.workflowservice.v1.SetWorkerDeploymentCurrentVersionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SetWorkerDeploymentCurrentVersionResponse:
        """Invokes the WorkflowService.set_worker_deployment_current_version rpc method."""
        ...
    
    async def set_worker_deployment_manager(self, req: temporalio.api.workflowservice.v1.SetWorkerDeploymentManagerRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SetWorkerDeploymentManagerResponse:
        """Invokes the WorkflowService.set_worker_deployment_manager rpc method."""
        ...
    
    async def set_worker_deployment_ramping_version(self, req: temporalio.api.workflowservice.v1.SetWorkerDeploymentRampingVersionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SetWorkerDeploymentRampingVersionResponse:
        """Invokes the WorkflowService.set_worker_deployment_ramping_version rpc method."""
        ...
    
    async def shutdown_worker(self, req: temporalio.api.workflowservice.v1.ShutdownWorkerRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.ShutdownWorkerResponse:
        """Invokes the WorkflowService.shutdown_worker rpc method."""
        ...
    
    async def signal_with_start_workflow_execution(self, req: temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SignalWithStartWorkflowExecutionResponse:
        """Invokes the WorkflowService.signal_with_start_workflow_execution rpc method."""
        ...
    
    async def signal_workflow_execution(self, req: temporalio.api.workflowservice.v1.SignalWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.SignalWorkflowExecutionResponse:
        """Invokes the WorkflowService.signal_workflow_execution rpc method."""
        ...
    
    async def start_batch_operation(self, req: temporalio.api.workflowservice.v1.StartBatchOperationRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.StartBatchOperationResponse:
        """Invokes the WorkflowService.start_batch_operation rpc method."""
        ...
    
    async def start_workflow_execution(self, req: temporalio.api.workflowservice.v1.StartWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.StartWorkflowExecutionResponse:
        """Invokes the WorkflowService.start_workflow_execution rpc method."""
        ...
    
    async def stop_batch_operation(self, req: temporalio.api.workflowservice.v1.StopBatchOperationRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.StopBatchOperationResponse:
        """Invokes the WorkflowService.stop_batch_operation rpc method."""
        ...
    
    async def terminate_workflow_execution(self, req: temporalio.api.workflowservice.v1.TerminateWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.TerminateWorkflowExecutionResponse:
        """Invokes the WorkflowService.terminate_workflow_execution rpc method."""
        ...
    
    async def trigger_workflow_rule(self, req: temporalio.api.workflowservice.v1.TriggerWorkflowRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.TriggerWorkflowRuleResponse:
        """Invokes the WorkflowService.trigger_workflow_rule rpc method."""
        ...
    
    async def unpause_activity(self, req: temporalio.api.workflowservice.v1.UnpauseActivityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UnpauseActivityResponse:
        """Invokes the WorkflowService.unpause_activity rpc method."""
        ...
    
    async def update_activity_options(self, req: temporalio.api.workflowservice.v1.UpdateActivityOptionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateActivityOptionsResponse:
        """Invokes the WorkflowService.update_activity_options rpc method."""
        ...
    
    async def update_namespace(self, req: temporalio.api.workflowservice.v1.UpdateNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateNamespaceResponse:
        """Invokes the WorkflowService.update_namespace rpc method."""
        ...
    
    async def update_schedule(self, req: temporalio.api.workflowservice.v1.UpdateScheduleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateScheduleResponse:
        """Invokes the WorkflowService.update_schedule rpc method."""
        ...
    
    async def update_task_queue_config(self, req: temporalio.api.workflowservice.v1.UpdateTaskQueueConfigRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateTaskQueueConfigResponse:
        """Invokes the WorkflowService.update_task_queue_config rpc method."""
        ...
    
    async def update_worker_build_id_compatibility(self, req: temporalio.api.workflowservice.v1.UpdateWorkerBuildIdCompatibilityRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkerBuildIdCompatibilityResponse:
        """Invokes the WorkflowService.update_worker_build_id_compatibility rpc method."""
        ...
    
    async def update_worker_config(self, req: temporalio.api.workflowservice.v1.UpdateWorkerConfigRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkerConfigResponse:
        """Invokes the WorkflowService.update_worker_config rpc method."""
        ...
    
    async def update_worker_deployment_version_metadata(self, req: temporalio.api.workflowservice.v1.UpdateWorkerDeploymentVersionMetadataRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkerDeploymentVersionMetadataResponse:
        """Invokes the WorkflowService.update_worker_deployment_version_metadata rpc method."""
        ...
    
    async def update_worker_versioning_rules(self, req: temporalio.api.workflowservice.v1.UpdateWorkerVersioningRulesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkerVersioningRulesResponse:
        """Invokes the WorkflowService.update_worker_versioning_rules rpc method."""
        ...
    
    async def update_workflow_execution(self, req: temporalio.api.workflowservice.v1.UpdateWorkflowExecutionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkflowExecutionResponse:
        """Invokes the WorkflowService.update_workflow_execution rpc method."""
        ...
    
    async def update_workflow_execution_options(self, req: temporalio.api.workflowservice.v1.UpdateWorkflowExecutionOptionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.workflowservice.v1.UpdateWorkflowExecutionOptionsResponse:
        """Invokes the WorkflowService.update_workflow_execution_options rpc method."""
        ...
    


class OperatorService:
    """RPC calls for the OperatorService."""
    def __init__(self, client: ServiceClient) -> None:
        """Initialize service with the provided ServiceClient."""
        ...
    
    async def add_or_update_remote_cluster(self, req: temporalio.api.operatorservice.v1.AddOrUpdateRemoteClusterRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.AddOrUpdateRemoteClusterResponse:
        """Invokes the OperatorService.add_or_update_remote_cluster rpc method."""
        ...
    
    async def add_search_attributes(self, req: temporalio.api.operatorservice.v1.AddSearchAttributesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.AddSearchAttributesResponse:
        """Invokes the OperatorService.add_search_attributes rpc method."""
        ...
    
    async def create_nexus_endpoint(self, req: temporalio.api.operatorservice.v1.CreateNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.CreateNexusEndpointResponse:
        """Invokes the OperatorService.create_nexus_endpoint rpc method."""
        ...
    
    async def delete_namespace(self, req: temporalio.api.operatorservice.v1.DeleteNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.DeleteNamespaceResponse:
        """Invokes the OperatorService.delete_namespace rpc method."""
        ...
    
    async def delete_nexus_endpoint(self, req: temporalio.api.operatorservice.v1.DeleteNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.DeleteNexusEndpointResponse:
        """Invokes the OperatorService.delete_nexus_endpoint rpc method."""
        ...
    
    async def get_nexus_endpoint(self, req: temporalio.api.operatorservice.v1.GetNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.GetNexusEndpointResponse:
        """Invokes the OperatorService.get_nexus_endpoint rpc method."""
        ...
    
    async def list_clusters(self, req: temporalio.api.operatorservice.v1.ListClustersRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.ListClustersResponse:
        """Invokes the OperatorService.list_clusters rpc method."""
        ...
    
    async def list_nexus_endpoints(self, req: temporalio.api.operatorservice.v1.ListNexusEndpointsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.ListNexusEndpointsResponse:
        """Invokes the OperatorService.list_nexus_endpoints rpc method."""
        ...
    
    async def list_search_attributes(self, req: temporalio.api.operatorservice.v1.ListSearchAttributesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.ListSearchAttributesResponse:
        """Invokes the OperatorService.list_search_attributes rpc method."""
        ...
    
    async def remove_remote_cluster(self, req: temporalio.api.operatorservice.v1.RemoveRemoteClusterRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.RemoveRemoteClusterResponse:
        """Invokes the OperatorService.remove_remote_cluster rpc method."""
        ...
    
    async def remove_search_attributes(self, req: temporalio.api.operatorservice.v1.RemoveSearchAttributesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.RemoveSearchAttributesResponse:
        """Invokes the OperatorService.remove_search_attributes rpc method."""
        ...
    
    async def update_nexus_endpoint(self, req: temporalio.api.operatorservice.v1.UpdateNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.operatorservice.v1.UpdateNexusEndpointResponse:
        """Invokes the OperatorService.update_nexus_endpoint rpc method."""
        ...
    


class CloudService:
    """RPC calls for the CloudService."""
    def __init__(self, client: ServiceClient) -> None:
        """Initialize service with the provided ServiceClient."""
        ...
    
    async def add_namespace_region(self, req: temporalio.api.cloud.cloudservice.v1.AddNamespaceRegionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.AddNamespaceRegionResponse:
        """Invokes the CloudService.add_namespace_region rpc method."""
        ...
    
    async def add_user_group_member(self, req: temporalio.api.cloud.cloudservice.v1.AddUserGroupMemberRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.AddUserGroupMemberResponse:
        """Invokes the CloudService.add_user_group_member rpc method."""
        ...
    
    async def create_api_key(self, req: temporalio.api.cloud.cloudservice.v1.CreateApiKeyRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateApiKeyResponse:
        """Invokes the CloudService.create_api_key rpc method."""
        ...
    
    async def create_connectivity_rule(self, req: temporalio.api.cloud.cloudservice.v1.CreateConnectivityRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateConnectivityRuleResponse:
        """Invokes the CloudService.create_connectivity_rule rpc method."""
        ...
    
    async def create_namespace(self, req: temporalio.api.cloud.cloudservice.v1.CreateNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateNamespaceResponse:
        """Invokes the CloudService.create_namespace rpc method."""
        ...
    
    async def create_namespace_export_sink(self, req: temporalio.api.cloud.cloudservice.v1.CreateNamespaceExportSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateNamespaceExportSinkResponse:
        """Invokes the CloudService.create_namespace_export_sink rpc method."""
        ...
    
    async def create_nexus_endpoint(self, req: temporalio.api.cloud.cloudservice.v1.CreateNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateNexusEndpointResponse:
        """Invokes the CloudService.create_nexus_endpoint rpc method."""
        ...
    
    async def create_service_account(self, req: temporalio.api.cloud.cloudservice.v1.CreateServiceAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateServiceAccountResponse:
        """Invokes the CloudService.create_service_account rpc method."""
        ...
    
    async def create_user(self, req: temporalio.api.cloud.cloudservice.v1.CreateUserRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateUserResponse:
        """Invokes the CloudService.create_user rpc method."""
        ...
    
    async def create_user_group(self, req: temporalio.api.cloud.cloudservice.v1.CreateUserGroupRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.CreateUserGroupResponse:
        """Invokes the CloudService.create_user_group rpc method."""
        ...
    
    async def delete_api_key(self, req: temporalio.api.cloud.cloudservice.v1.DeleteApiKeyRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteApiKeyResponse:
        """Invokes the CloudService.delete_api_key rpc method."""
        ...
    
    async def delete_connectivity_rule(self, req: temporalio.api.cloud.cloudservice.v1.DeleteConnectivityRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteConnectivityRuleResponse:
        """Invokes the CloudService.delete_connectivity_rule rpc method."""
        ...
    
    async def delete_namespace(self, req: temporalio.api.cloud.cloudservice.v1.DeleteNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteNamespaceResponse:
        """Invokes the CloudService.delete_namespace rpc method."""
        ...
    
    async def delete_namespace_export_sink(self, req: temporalio.api.cloud.cloudservice.v1.DeleteNamespaceExportSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteNamespaceExportSinkResponse:
        """Invokes the CloudService.delete_namespace_export_sink rpc method."""
        ...
    
    async def delete_namespace_region(self, req: temporalio.api.cloud.cloudservice.v1.DeleteNamespaceRegionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteNamespaceRegionResponse:
        """Invokes the CloudService.delete_namespace_region rpc method."""
        ...
    
    async def delete_nexus_endpoint(self, req: temporalio.api.cloud.cloudservice.v1.DeleteNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteNexusEndpointResponse:
        """Invokes the CloudService.delete_nexus_endpoint rpc method."""
        ...
    
    async def delete_service_account(self, req: temporalio.api.cloud.cloudservice.v1.DeleteServiceAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteServiceAccountResponse:
        """Invokes the CloudService.delete_service_account rpc method."""
        ...
    
    async def delete_user(self, req: temporalio.api.cloud.cloudservice.v1.DeleteUserRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteUserResponse:
        """Invokes the CloudService.delete_user rpc method."""
        ...
    
    async def delete_user_group(self, req: temporalio.api.cloud.cloudservice.v1.DeleteUserGroupRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.DeleteUserGroupResponse:
        """Invokes the CloudService.delete_user_group rpc method."""
        ...
    
    async def failover_namespace_region(self, req: temporalio.api.cloud.cloudservice.v1.FailoverNamespaceRegionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.FailoverNamespaceRegionResponse:
        """Invokes the CloudService.failover_namespace_region rpc method."""
        ...
    
    async def get_account(self, req: temporalio.api.cloud.cloudservice.v1.GetAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetAccountResponse:
        """Invokes the CloudService.get_account rpc method."""
        ...
    
    async def get_api_key(self, req: temporalio.api.cloud.cloudservice.v1.GetApiKeyRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetApiKeyResponse:
        """Invokes the CloudService.get_api_key rpc method."""
        ...
    
    async def get_api_keys(self, req: temporalio.api.cloud.cloudservice.v1.GetApiKeysRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetApiKeysResponse:
        """Invokes the CloudService.get_api_keys rpc method."""
        ...
    
    async def get_async_operation(self, req: temporalio.api.cloud.cloudservice.v1.GetAsyncOperationRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetAsyncOperationResponse:
        """Invokes the CloudService.get_async_operation rpc method."""
        ...
    
    async def get_connectivity_rule(self, req: temporalio.api.cloud.cloudservice.v1.GetConnectivityRuleRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetConnectivityRuleResponse:
        """Invokes the CloudService.get_connectivity_rule rpc method."""
        ...
    
    async def get_connectivity_rules(self, req: temporalio.api.cloud.cloudservice.v1.GetConnectivityRulesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetConnectivityRulesResponse:
        """Invokes the CloudService.get_connectivity_rules rpc method."""
        ...
    
    async def get_namespace(self, req: temporalio.api.cloud.cloudservice.v1.GetNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNamespaceResponse:
        """Invokes the CloudService.get_namespace rpc method."""
        ...
    
    async def get_namespace_export_sink(self, req: temporalio.api.cloud.cloudservice.v1.GetNamespaceExportSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNamespaceExportSinkResponse:
        """Invokes the CloudService.get_namespace_export_sink rpc method."""
        ...
    
    async def get_namespace_export_sinks(self, req: temporalio.api.cloud.cloudservice.v1.GetNamespaceExportSinksRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNamespaceExportSinksResponse:
        """Invokes the CloudService.get_namespace_export_sinks rpc method."""
        ...
    
    async def get_namespaces(self, req: temporalio.api.cloud.cloudservice.v1.GetNamespacesRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNamespacesResponse:
        """Invokes the CloudService.get_namespaces rpc method."""
        ...
    
    async def get_nexus_endpoint(self, req: temporalio.api.cloud.cloudservice.v1.GetNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNexusEndpointResponse:
        """Invokes the CloudService.get_nexus_endpoint rpc method."""
        ...
    
    async def get_nexus_endpoints(self, req: temporalio.api.cloud.cloudservice.v1.GetNexusEndpointsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetNexusEndpointsResponse:
        """Invokes the CloudService.get_nexus_endpoints rpc method."""
        ...
    
    async def get_region(self, req: temporalio.api.cloud.cloudservice.v1.GetRegionRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetRegionResponse:
        """Invokes the CloudService.get_region rpc method."""
        ...
    
    async def get_regions(self, req: temporalio.api.cloud.cloudservice.v1.GetRegionsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetRegionsResponse:
        """Invokes the CloudService.get_regions rpc method."""
        ...
    
    async def get_service_account(self, req: temporalio.api.cloud.cloudservice.v1.GetServiceAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetServiceAccountResponse:
        """Invokes the CloudService.get_service_account rpc method."""
        ...
    
    async def get_service_accounts(self, req: temporalio.api.cloud.cloudservice.v1.GetServiceAccountsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetServiceAccountsResponse:
        """Invokes the CloudService.get_service_accounts rpc method."""
        ...
    
    async def get_usage(self, req: temporalio.api.cloud.cloudservice.v1.GetUsageRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUsageResponse:
        """Invokes the CloudService.get_usage rpc method."""
        ...
    
    async def get_user(self, req: temporalio.api.cloud.cloudservice.v1.GetUserRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUserResponse:
        """Invokes the CloudService.get_user rpc method."""
        ...
    
    async def get_user_group(self, req: temporalio.api.cloud.cloudservice.v1.GetUserGroupRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUserGroupResponse:
        """Invokes the CloudService.get_user_group rpc method."""
        ...
    
    async def get_user_group_members(self, req: temporalio.api.cloud.cloudservice.v1.GetUserGroupMembersRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUserGroupMembersResponse:
        """Invokes the CloudService.get_user_group_members rpc method."""
        ...
    
    async def get_user_groups(self, req: temporalio.api.cloud.cloudservice.v1.GetUserGroupsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUserGroupsResponse:
        """Invokes the CloudService.get_user_groups rpc method."""
        ...
    
    async def get_users(self, req: temporalio.api.cloud.cloudservice.v1.GetUsersRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.GetUsersResponse:
        """Invokes the CloudService.get_users rpc method."""
        ...
    
    async def remove_user_group_member(self, req: temporalio.api.cloud.cloudservice.v1.RemoveUserGroupMemberRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.RemoveUserGroupMemberResponse:
        """Invokes the CloudService.remove_user_group_member rpc method."""
        ...
    
    async def rename_custom_search_attribute(self, req: temporalio.api.cloud.cloudservice.v1.RenameCustomSearchAttributeRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.RenameCustomSearchAttributeResponse:
        """Invokes the CloudService.rename_custom_search_attribute rpc method."""
        ...
    
    async def set_service_account_namespace_access(self, req: temporalio.api.cloud.cloudservice.v1.SetServiceAccountNamespaceAccessRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.SetServiceAccountNamespaceAccessResponse:
        """Invokes the CloudService.set_service_account_namespace_access rpc method."""
        ...
    
    async def set_user_group_namespace_access(self, req: temporalio.api.cloud.cloudservice.v1.SetUserGroupNamespaceAccessRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.SetUserGroupNamespaceAccessResponse:
        """Invokes the CloudService.set_user_group_namespace_access rpc method."""
        ...
    
    async def set_user_namespace_access(self, req: temporalio.api.cloud.cloudservice.v1.SetUserNamespaceAccessRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.SetUserNamespaceAccessResponse:
        """Invokes the CloudService.set_user_namespace_access rpc method."""
        ...
    
    async def update_account(self, req: temporalio.api.cloud.cloudservice.v1.UpdateAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateAccountResponse:
        """Invokes the CloudService.update_account rpc method."""
        ...
    
    async def update_api_key(self, req: temporalio.api.cloud.cloudservice.v1.UpdateApiKeyRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateApiKeyResponse:
        """Invokes the CloudService.update_api_key rpc method."""
        ...
    
    async def update_namespace(self, req: temporalio.api.cloud.cloudservice.v1.UpdateNamespaceRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateNamespaceResponse:
        """Invokes the CloudService.update_namespace rpc method."""
        ...
    
    async def update_namespace_export_sink(self, req: temporalio.api.cloud.cloudservice.v1.UpdateNamespaceExportSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateNamespaceExportSinkResponse:
        """Invokes the CloudService.update_namespace_export_sink rpc method."""
        ...
    
    async def update_namespace_tags(self, req: temporalio.api.cloud.cloudservice.v1.UpdateNamespaceTagsRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateNamespaceTagsResponse:
        """Invokes the CloudService.update_namespace_tags rpc method."""
        ...
    
    async def update_nexus_endpoint(self, req: temporalio.api.cloud.cloudservice.v1.UpdateNexusEndpointRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateNexusEndpointResponse:
        """Invokes the CloudService.update_nexus_endpoint rpc method."""
        ...
    
    async def update_service_account(self, req: temporalio.api.cloud.cloudservice.v1.UpdateServiceAccountRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateServiceAccountResponse:
        """Invokes the CloudService.update_service_account rpc method."""
        ...
    
    async def update_user(self, req: temporalio.api.cloud.cloudservice.v1.UpdateUserRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateUserResponse:
        """Invokes the CloudService.update_user rpc method."""
        ...
    
    async def update_user_group(self, req: temporalio.api.cloud.cloudservice.v1.UpdateUserGroupRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.UpdateUserGroupResponse:
        """Invokes the CloudService.update_user_group rpc method."""
        ...
    
    async def validate_account_audit_log_sink(self, req: temporalio.api.cloud.cloudservice.v1.ValidateAccountAuditLogSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.ValidateAccountAuditLogSinkResponse:
        """Invokes the CloudService.validate_account_audit_log_sink rpc method."""
        ...
    
    async def validate_namespace_export_sink(self, req: temporalio.api.cloud.cloudservice.v1.ValidateNamespaceExportSinkRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.cloud.cloudservice.v1.ValidateNamespaceExportSinkResponse:
        """Invokes the CloudService.validate_namespace_export_sink rpc method."""
        ...
    


class TestService:
    """RPC calls for the TestService."""
    def __init__(self, client: ServiceClient) -> None:
        """Initialize service with the provided ServiceClient."""
        ...
    
    async def get_current_time(self, req: google.protobuf.empty_pb2.Empty, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.GetCurrentTimeResponse:
        """Invokes the TestService.get_current_time rpc method."""
        ...
    
    async def lock_time_skipping(self, req: temporalio.api.testservice.v1.LockTimeSkippingRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.LockTimeSkippingResponse:
        """Invokes the TestService.lock_time_skipping rpc method."""
        ...
    
    async def sleep(self, req: temporalio.api.testservice.v1.SleepRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.SleepResponse:
        """Invokes the TestService.sleep rpc method."""
        ...
    
    async def sleep_until(self, req: temporalio.api.testservice.v1.SleepUntilRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.SleepResponse:
        """Invokes the TestService.sleep_until rpc method."""
        ...
    
    async def unlock_time_skipping(self, req: temporalio.api.testservice.v1.UnlockTimeSkippingRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.UnlockTimeSkippingResponse:
        """Invokes the TestService.unlock_time_skipping rpc method."""
        ...
    
    async def unlock_time_skipping_with_sleep(self, req: temporalio.api.testservice.v1.SleepRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.api.testservice.v1.SleepResponse:
        """Invokes the TestService.unlock_time_skipping_with_sleep rpc method."""
        ...
    


class HealthService:
    """RPC calls for the HealthService."""
    def __init__(self, client: ServiceClient) -> None:
        """Initialize service with the provided ServiceClient."""
        ...
    
    async def check(self, req: temporalio.bridge.proto.health.v1.HealthCheckRequest, retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> temporalio.bridge.proto.health.v1.HealthCheckResponse:
        """Invokes the HealthService.check rpc method."""
        ...
    


