"""
This type stub file was generated by pyright.
"""

import grpc
from .request_response_pb2 import GetCurrentTimeResponse, LockTimeSkippingRequest, LockTimeSkippingResponse, SleepRequest, SleepResponse, SleepUntilRequest, UnlockTimeSkippingRequest, UnlockTimeSkippingResponse
from .service_pb2_grpc import TestServiceServicer, TestServiceStub, add_TestServiceServicer_to_server

__all__ = ["GetCurrentTimeResponse", "LockTimeSkippingRequest", "LockTimeSkippingResponse", "SleepRequest", "SleepResponse", "SleepUntilRequest", "UnlockTimeSkippingRequest", "UnlockTimeSkippingResponse"]
