"""
This type stub file was generated by pyright.
"""

from .message_pb2 import AllowedCloudNamespacePolicySpec, Endpoint, EndpointPolicySpec, EndpointSpec, EndpointTargetSpec, WorkerTargetSpec

__all__ = ["AllowedCloudNamespacePolicySpec", "Endpoint", "EndpointPolicySpec", "EndpointSpec", "EndpointTargetSpec", "WorkerTargetSpec"]
