services:
  elasticsearch:
    container_name: resilmesh_sap_wo_elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:${ELASTICSEARCH_VERSION:-8.9.0}
    expose:
      - 9200
    volumes:
      - /var/lib/elasticsearch/data
    networks:
      - resilmesh_network

  postgresql:
    container_name: resilmesh_sap_wo_postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION:-17}
    expose:
      - 5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - resilmesh_network

  resilmesh_sap_wo_temporal:
    container_name: resilmesh_sap_wo_temporal
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=resilmesh_sap_wo_postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - ENABLE_ES=true
      - ES_SEEDS=resilmesh_sap_wo_elasticsearch
      - ES_VERSION=v7
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-1.22.7}
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap
    volumes:
      - ./temporalio/dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - resilmesh_network
    healthcheck:
      test: ["CMD","tctl", "--address", "resilmesh_sap_wo_temporal:7233", "workflow", "list", "||", "exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  resilmesh_sap_wo_temporal_admin:
    container_name: resilmesh_sap_wo_temporal_admin
    depends_on:
      - resilmesh_sap_wo_temporal
    environment:
      - TEMPORAL_ADDRESS=resilmesh_sap_wo_temporal:7233
      - TEMPORAL_CLI_ADDRESS=resilmesh_sap_wo_temporal:7233
    image: temporalio/admin-tools:${TEMPORAL_VERSION:-1.22.7}
    stdin_open: true
    tty: true
    networks:
      - resilmesh_network

  resilmesh_sap_wo_temporal_ui:
    container_name: resilmesh_sap_wo_temporal_ui
    depends_on:
      - resilmesh_sap_wo_temporal
    environment:
      - TEMPORAL_ADDRESS=resilmesh_sap_wo_temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000, http://localhost:4201, http://localhost:3000, http://localhost:5000
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-2.31.2}
    ports:
      - 8080:8080
    networks:
      - resilmesh_network

  resilmesh_sap_wo_postgres:
    container_name: resilmesh_sap_wo_postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: amass
      PG_DATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/install_extensions.sql:/docker-entrypoint-initdb.d/install_extensions.sql
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - resilmesh_network

  resilmesh_sap_wo_worker:
    container_name: resilmesh_sap_wo_worker
    build: 
      context: .
      dockerfile: Dockerfile
      network: host
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
      - ./docker/amass_config.yaml:/app/.config/amass/config.yaml
    depends_on:
      resilmesh_sap_wo_temporal:
        condition: service_healthy
    networks:
      - resilmesh_network

#  metasploitable3:
#    image: kirscht/metasploitable3-ub1404
#    container_name: metasploitable3
#    entrypoint: /entrypoint.sh
#    environment:
#      PASS: myPass
#      ROOT: yes
#      CUPS: yes
#      FTP: yes
#      HTTP: yes
#      IRC: yes
#      SMB: yes
#      SSH: yes
#      SQL: yes
#    networks:
#      resilmesh_network:

  resilmesh_sap_wo_redis:
    container_name: resilmesh_sap_wo_redis
    image: redis:7.0-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - resilmesh_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  resilmesh_sap_wo_component_scheduler:
    container_name: resilmesh_sap_wo_component_scheduler
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    command: ["/venv/bin/python", "/app/component_worker.py"]
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ../ISIM/config:/config:ro
    depends_on:
      resilmesh_sap_wo_temporal:
        condition: service_healthy
    networks:
      - resilmesh_network
    environment:
      - TEMPORAL_HOST=resilmesh_sap_wo_temporal
      - TEMPORAL_PORT=7233
      - TEMPORAL_NAMESPACE=default
      - RISK_API_URL=http://resilmesh_sap_isim_automation:5000
      - NEO4J_URI=bolt://resilmesh_sap_isim_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo

  resilmesh_sap_wo_nmap:
    container_name: resilmesh_sap_wo_nmap
    build:
      dockerfile: nmap.Dockerfile
      network: host
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
    depends_on:
      resilmesh_sap_wo_temporal:
        condition: service_healthy
    networks:
      - resilmesh_network
    environment:
      - NVD_KEY
      - TEMPORAL_HOST=resilmesh_sap_wo_temporal
      - TEMPORAL_PORT=7233
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - NEO4J_BOLT=bolt://resilmesh_sap_isim_neo4j:7687

  resilmesh_sap_wo_cve_connector:
    container_name: resilmesh_sap_wo_cve_connector
    build:
      dockerfile: cve-connector.Dockerfile
      network: host
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
    depends_on:
      resilmesh_sap_wo_temporal:
        condition: service_healthy
    networks:
      - resilmesh_network
    environment:
      - NVD_KEY
      - TEMPORAL_HOST=resilmesh_sap_wo_temporal
      - TEMPORAL_PORT=7233
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - NEO4J_BOLT=bolt://resilmesh_sap_isim_neo4j:7687

volumes:
  resilmesh_sap_wo_neo4j_data:

networks:
  resilmesh_network:
    external: true