services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: amass
      PG_DATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql/install_extensions.sql:/docker-entrypoint-initdb.d/install_extensions.sql
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - resilmesh_network

  worker:
    build: .
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
      - ./docker/amass_config.yaml:/app/.config/amass/config.yaml
    networks:
      - resilmesh_network

#  metasploitable3:
#    image: kirscht/metasploitable3-ub1404
#    container_name: metasploitable3
#    # use environment variables to set password, enable root and start services
#    entrypoint: /entrypoint.sh
#    environment:
#      PASS: myPass
#      ROOT: yes
#      CUPS: yes
#      FTP: yes
#      HTTP: yes
#      IRC: yes
#      SMB: yes
#      SSH: yes
#      SQL: yes
#    networks:
#      casm_isim_test_network:



#  neo4j:
#    image: neo4j:5.21.0
#    environment:
#      - NEO4J_AUTH=neo4j/supertestovaciheslo
#      - NEO4J_PLUGINS=["apoc"]
#      - NEO4J_apoc_export_file_enabled=true
#      - NEO4J_apoc_import_file_enabled=true
#      - NEO4J_apoc_import_file_use__neo4j__config=true
#    volumes:
#      - neo4j_easyeasm_data:/data
#    ports:
#      - 7474:7474
#      - 7687:7687
#    healthcheck:
#      test: ["CMD", "wget", "http://localhost:7474/"]
#      interval: 10s
#      timeout: 2s
#      retries: 10
#    restart: unless-stopped
#    networks:
#      - casm_isim_test_network

  redis:
    image: docker.io/redis:7
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - resilmesh_network

  nmap-worker:
    build:
      dockerfile: nmap.Dockerfile
    container_name: nmap-worker
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
    networks:
      - resilmesh_network
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - NEO4J_BOLT=bolt://neo4j:7687

  cve-connector-worker:
    build:
      dockerfile: cve-connector.Dockerfile
    container_name: cve-connector
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
#    depends_on:
#      neo4j:
    networks:
      - resilmesh_network
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supertestovaciheslo
      - NEO4J_BOLT=bolt://neo4j:7687

  slp-enrichment-worker:
    build:
      dockerfile: slp_enrichment.Dockerfile
    container_name: slp-enrichment
    restart: unless-stopped
    volumes:
      - ./docker/config.yaml:/app/config/config.yaml
    networks:
      - resilmesh_network
    environment:
      - TEMPORAL_HOST=temporal
      - TEMPORAL_PORT=7233

volumes:
  neo4j_easyeasm_data:

networks:
  resilmesh_network:
    name: resilmesh_network