[tool.poetry]
name = "easyeasm-demo"
version = "0.1.0"
description = ""
authors = ["Michal Čech <445431@mail.muni.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
temporalio = "^1.8.0"
click = "^8.1.7"
pyyaml = "^6.0.2"
dacite = "^1.8.1"
redis = "^5.1.1"
neo4j = "^5.25.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
