FROM python:3.13-bookworm AS build

WORKDIR /app-1

ENV PIP_DEFAULT_TIMEOUT=100 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_NO_CACHE_DIR=1

COPY cve_connector/requirements.txt cve_connector/
COPY cve_connector/setup.py cve_connector/

RUN python -m venv /venv
RUN /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install -r cve_connector/requirements.txt
RUN /venv/bin/pip install temporalio==1.11.0

COPY cve_connector/ cve_connector/

RUN /venv/bin/pip install cve_connector/

FROM python:3.13-bookworm

WORKDIR /app

COPY --from=build /venv /venv

COPY cve_connector/ cve_connector/

ENV PATH="/venv/bin:$PATH"

CMD ["python", "-m", "cve_connector.cve_temporal"]
