"""
This type stub file was generated by pyright.
"""

from .common_pb2 import NamespacedWorkflowExecution, VersioningIntent, WorkerDeploymentVersion

__all__ = ["NamespacedWorkflowExecution", "VersioningIntent", "WorkerDeploymentVersion"]
