"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _VersioningIntent:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _VersioningIntentEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VersioningIntent.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNSPECIFIED: _VersioningIntent.ValueType
    COMPATIBLE: _VersioningIntent.ValueType
    DEFAULT: _VersioningIntent.ValueType
    ...


class VersioningIntent(_VersioningIntent, metaclass=_VersioningIntentEnumTypeWrapper):
    """An indication of user's intent concerning what Build ID versioning approach should be used for
    a specific command
    """
    ...


UNSPECIFIED: VersioningIntent.ValueType
COMPATIBLE: VersioningIntent.ValueType
DEFAULT: VersioningIntent.ValueType
global___VersioningIntent = VersioningIntent
class NamespacedWorkflowExecution(google.protobuf.message.Message):
    """Identifying information about a particular workflow execution, including namespace"""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAMESPACE_FIELD_NUMBER: builtins.int
    WORKFLOW_ID_FIELD_NUMBER: builtins.int
    RUN_ID_FIELD_NUMBER: builtins.int
    namespace: builtins.str
    workflow_id: builtins.str
    run_id: builtins.str
    def __init__(self, *, namespace: builtins.str = ..., workflow_id: builtins.str = ..., run_id: builtins.str = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["namespace", b"namespace", "run_id", b"run_id", "workflow_id", b"workflow_id",]) -> None:
        ...
    


global___NamespacedWorkflowExecution = NamespacedWorkflowExecution
class WorkerDeploymentVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DEPLOYMENT_NAME_FIELD_NUMBER: builtins.int
    BUILD_ID_FIELD_NUMBER: builtins.int
    deployment_name: builtins.str
    build_id: builtins.str
    def __init__(self, *, deployment_name: builtins.str = ..., build_id: builtins.str = ...) -> None:
        ...
    
    def ClearField(self, field_name: typing_extensions.Literal["build_id", b"build_id", "deployment_name", b"deployment_name"]) -> None:
        ...
    


global___WorkerDeploymentVersion = WorkerDeploymentVersion
