"""
This type stub file was generated by pyright.
"""

from ._activity import SharedHeartbeatSender, SharedStateManager
from ._interceptor import ActivityInboundInterceptor, ActivityOutboundInterceptor, ContinueAsNewInput, ExecuteActivityInput, ExecuteWorkflowInput, HandleQueryInput, HandleSignalInput, HandleUpdateInput, Interceptor, SignalChildWorkflowInput, SignalExternalWorkflowInput, StartActivityInput, StartChildWorkflowInput, StartLocalActivityInput, StartNexusOperationInput, WorkflowInboundInterceptor, WorkflowInterceptorClassInput, WorkflowOutboundInterceptor
from ._plugin import Plugin
from ._replayer import Replayer, ReplayerConfig, WorkflowReplayResult, WorkflowReplayResults
from ._tuning import ActivitySlotInfo, CustomSlotSupplier, FixedSizeSlotSupplier, LocalActivitySlotInfo, NexusSlotInfo, ResourceBasedSlotConfig, ResourceBasedSlotSupplier, ResourceBasedTunerConfig, SlotInfo, SlotMarkUsedContext, SlotPermit, SlotReleaseContext, SlotReserveContext, WorkerTuner, WorkflowSlotInfo
from ._worker import PollerBehavior, PollerBehaviorAutoscaling, PollerBehaviorSimpleMaximum, Worker, WorkerConfig, WorkerDeploymentConfig, WorkerDeploymentVersion
from ._workflow_instance import UnsandboxedWorkflowRunner, WorkflowInstance, WorkflowInstanceDetails, WorkflowRunner

"""Worker for processing Temporal workflows and/or activities."""
__all__ = ["Worker", "WorkerConfig", "WorkerDeploymentConfig", "WorkerDeploymentVersion", "Replayer", "ReplayerConfig", "WorkflowReplayResult", "WorkflowReplayResults", "PollerBehavior", "PollerBehaviorSimpleMaximum", "PollerBehaviorAutoscaling", "Interceptor", "ActivityInboundInterceptor", "ActivityOutboundInterceptor", "WorkflowInboundInterceptor", "WorkflowOutboundInterceptor", "Plugin", "ContinueAsNewInput", "ExecuteActivityInput", "ExecuteWorkflowInput", "HandleQueryInput", "HandleSignalInput", "HandleUpdateInput", "SignalChildWorkflowInput", "SignalExternalWorkflowInput", "StartActivityInput", "StartChildWorkflowInput", "StartLocalActivityInput", "StartNexusOperationInput", "WorkflowInterceptorClassInput", "SharedStateManager", "SharedHeartbeatSender", "WorkflowRunner", "WorkflowInstance", "WorkflowInstanceDetails", "UnsandboxedWorkflowRunner", "WorkerTuner", "FixedSizeSlotSupplier", "ResourceBasedSlotSupplier", "ResourceBasedTunerConfig", "ResourceBasedSlotConfig", "ActivitySlotInfo", "CustomSlotSupplier", "LocalActivitySlotInfo", "SlotInfo", "SlotMarkUsedContext", "SlotPermit", "SlotReleaseContext", "SlotReserveContext", "WorkflowSlotInfo", "NexusSlotInfo"]
