"""
This type stub file was generated by pyright.
"""

import contextvars
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Iterator, Optional
from temporalio.api.enums.v1.command_type_pb2 import CommandType
from temporalio.bridge._visitor import PayloadVisitor

"""Visitor that sets command context during payload traversal."""
@dataclass(frozen=True)
class CommandInfo:
    """Information identifying a specific command instance."""
    command_type: CommandType.ValueType
    command_seq: int
    ...


current_command_info: contextvars.ContextVar[Optional[CommandInfo]] = ...
class CommandAwarePayloadVisitor(PayloadVisitor):
    """Payload visitor that sets command context during traversal.

    Override methods are explicitly defined for workflow commands and
    activation jobs that have both a 'seq' field and payloads to visit.
    """
    ...


@contextmanager
def current_command(command_type: CommandType.ValueType, command_seq: int) -> Iterator[None]:
    """Context manager for setting command info."""
    ...

