"""
This type stub file was generated by pyright.
"""

import asyncio
import concurrent.futures
import nexusrpc.handler
import temporalio.api.common.v1
import temporalio.bridge.worker
import temporalio.client
import temporalio.common
import temporalio.converter
from dataclasses import dataclass
from typing import Any, Callable, Optional, Sequence, Type
from ._interceptor import Interceptor

"""Nexus worker"""
_TEMPORAL_FAILURE_PROTO_TYPE = ...
@dataclass
class _RunningNexusTask:
    task: asyncio.Task[Any]
    cancellation: _NexusTaskCancellation
    def cancel(self, reason: str): # -> None:
        ...
    


class _NexusWorker:
    def __init__(self, *, bridge_worker: Callable[[], temporalio.bridge.worker.Worker], client: temporalio.client.Client, task_queue: str, service_handlers: Sequence[Any], data_converter: temporalio.converter.DataConverter, interceptors: Sequence[Interceptor], metric_meter: temporalio.common.MetricMeter, executor: Optional[concurrent.futures.Executor]) -> None:
        ...
    
    async def run(self) -> None:
        """Continually poll for Nexus tasks and dispatch to handlers."""
        ...
    
    async def drain_poll_queue(self) -> None:
        ...
    
    async def wait_all_completed(self) -> None:
        ...
    


@dataclass
class _DummyPayloadSerializer:
    data_converter: temporalio.converter.DataConverter
    payload: temporalio.api.common.v1.Payload
    async def serialize(self, value: Any) -> nexusrpc.Content:
        ...
    
    async def deserialize(self, content: nexusrpc.Content, as_type: Optional[Type[Any]] = ...) -> Any:
        ...
    


class _NexusTaskCancellation(nexusrpc.handler.OperationTaskCancellation):
    def __init__(self) -> None:
        ...
    
    def is_cancelled(self) -> bool:
        ...
    
    def cancellation_reason(self) -> Optional[str]:
        ...
    
    def wait_until_cancelled_sync(self, timeout: float | None = ...) -> bool:
        ...
    
    async def wait_until_cancelled(self) -> None:
        ...
    
    def cancel(self, reason: str) -> bool:
        ...
    


