"""
This type stub file was generated by pyright.
"""

import concurrent.futures
import temporalio.api.common.v1
import temporalio.bridge.proto.workflow_activation
import temporalio.bridge.proto.workflow_completion
import temporalio.bridge.worker
import temporalio.common
import temporalio.converter
from dataclasses import dataclass
from types import TracebackType
from typing import Callable, List, Optional, Sequence, Set, Type
from ._interceptor import Interceptor
from ._workflow_instance import WorkflowInstance, WorkflowRunner

"""Workflow worker."""
logger = ...
LOG_PROTOS = ...
class _WorkflowWorker:
    def __init__(self, *, bridge_worker: Callable[[], temporalio.bridge.worker.Worker], namespace: str, task_queue: str, workflows: Sequence[Type], workflow_task_executor: Optional[concurrent.futures.ThreadPoolExecutor], max_concurrent_workflow_tasks: Optional[int], workflow_runner: WorkflowRunner, unsandboxed_workflow_runner: WorkflowRunner, data_converter: temporalio.converter.DataConverter, interceptors: Sequence[Interceptor], workflow_failure_exception_types: Sequence[Type[BaseException]], debug_mode: bool, disable_eager_activity_execution: bool, metric_meter: temporalio.common.MetricMeter, on_eviction_hook: Optional[Callable[[str, temporalio.bridge.proto.workflow_activation.RemoveFromCache], None]], disable_safe_eviction: bool, should_enforce_versioning_behavior: bool, assert_local_activity_valid: Callable[[str], None], encode_headers: bool) -> None:
        ...
    
    async def run(self) -> None:
        ...
    
    def notify_shutdown(self) -> None:
        ...
    
    async def drain_poll_queue(self) -> None:
        ...
    
    def nondeterminism_as_workflow_fail(self) -> bool:
        ...
    
    def nondeterminism_as_workflow_fail_for_types(self) -> Set[str]:
        ...
    


class _DeadlockError(Exception):
    """Exception class for deadlocks. Contains functionality to swap the default traceback for another."""
    def __init__(self, message: str, replacement_tb: Optional[TracebackType] = ...) -> None:
        """Create a new DeadlockError, with message `message` and optionally a traceback `replacement_tb` to be swapped in later.

        Args:
            message: Message to be presented through exception.
            replacement_tb: Optional TracebackType to be swapped later.
        """
        ...
    
    def swap_traceback(self) -> None:
        """Swap the current traceback for the replacement passed during construction. Used to work around Python adding the current frame to the stack trace.

        Returns:
            None
        """
        ...
    
    @classmethod
    def from_deadlocked_workflow(cls, workflow: WorkflowInstance, timeout: Optional[int]): # -> Self:
        ...
    


class _RunningWorkflow:
    def __init__(self, instance: WorkflowInstance, workflow_id: str) -> None:
        ...
    
    def activate(self, act: temporalio.bridge.proto.workflow_activation.WorkflowActivation) -> temporalio.bridge.proto.workflow_completion.WorkflowActivationCompletion:
        ...
    
    def attempt_deadlock_interruption(self) -> None:
        ...
    


@dataclass(frozen=True)
class _CommandAwarePayloadCodec(temporalio.converter.PayloadCodec):
    """A payload codec that sets serialization context for the command associated with each payload.

    This codec responds to the context variable set by
    :py:class:`_command_aware_visitor.CommandAwarePayloadVisitor`.
    """
    instance: WorkflowInstance
    context_free_payload_codec: temporalio.converter.PayloadCodec
    workflow_context_payload_codec: temporalio.converter.PayloadCodec
    workflow_context: temporalio.converter.WorkflowSerializationContext
    async def encode(self, payloads: Sequence[temporalio.api.common.v1.Payload]) -> List[temporalio.api.common.v1.Payload]:
        ...
    
    async def decode(self, payloads: Sequence[temporalio.api.common.v1.Payload]) -> List[temporalio.api.common.v1.Payload]:
        ...
    


class _InterruptDeadlockError(BaseException):
    ...


