"""
This type stub file was generated by pyright.
"""

import asyncio
import contextvars
import random
import temporalio.api.common.v1
import temporalio.api.sdk.v1
import temporalio.bridge.proto.activity_result
import temporalio.bridge.proto.workflow_activation
import temporalio.bridge.proto.workflow_completion
import temporalio.common
import temporalio.converter
import temporalio.workflow
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import timedelta
from enum import IntEnum
from typing import Any, Awaitable, Callable, Coroutine, Dict, Generator, Generic, Mapping, NoReturn, Optional, Sequence, Type, TypeVar, Union
from nexusrpc import InputT, OutputT
from typing_extensions import Self, TypeAlias, TypeVarTuple, TypedDict, Unpack
from ..api.failure.v1.message_pb2 import Failure
from . import _command_aware_visitor
from ._interceptor import ContinueAsNewInput, ExecuteWorkflowInput, HandleQueryInput, HandleSignalInput, HandleUpdateInput, SignalChildWorkflowInput, SignalExternalWorkflowInput, StartActivityInput, StartChildWorkflowInput, StartLocalActivityInput, StartNexusOperationInput, WorkflowInboundInterceptor, WorkflowOutboundInterceptor

"""Workflow worker runner and instance."""
logger = ...
LOG_IGNORE_DURING_DELETE = ...
class WorkflowRunner(ABC):
    """Abstract runner for workflows that creates workflow instances to run.

    :py:class:`UnsandboxedWorkflowRunner` is an implementation that locally runs
    the workflow.
    """
    @abstractmethod
    def prepare_workflow(self, defn: temporalio.workflow._Definition) -> None:
        """Prepare a workflow for future execution.

        This is run once for each workflow definition when a worker starts. This
        allows the runner to do anything necessarily to prepare for this
        definition to be used multiple times in create_instance.

        Args:
            defn: The workflow definition.
        """
        ...
    
    @abstractmethod
    def create_instance(self, det: WorkflowInstanceDetails) -> WorkflowInstance:
        """Create a workflow instance that can handle activations.

        Args:
            det: Details that can be used to create the instance.

        Returns:
            Workflow instance that can handle activations.
        """
        ...
    
    def set_worker_level_failure_exception_types(self, types: Sequence[Type[BaseException]]) -> None:
        """Set worker-level failure exception types that will be used to
        validate in the sandbox when calling ``prepare_workflow``.

        Args:
            types: Exception types.
        """
        ...
    


@dataclass(frozen=True)
class WorkflowInstanceDetails:
    """Immutable details for creating a workflow instance."""
    payload_converter_class: Type[temporalio.converter.PayloadConverter]
    failure_converter_class: Type[temporalio.converter.FailureConverter]
    interceptor_classes: Sequence[Type[WorkflowInboundInterceptor]]
    defn: temporalio.workflow._Definition
    info: temporalio.workflow.Info
    randomness_seed: int
    extern_functions: Mapping[str, Callable]
    disable_eager_activity_execution: bool
    worker_level_failure_exception_types: Sequence[Type[BaseException]]
    last_completion_result: temporalio.api.common.v1.Payloads
    last_failure: Optional[Failure]
    ...


class WorkflowInstance(ABC):
    """Instance of a workflow that can handle activations."""
    @abstractmethod
    def activate(self, act: temporalio.bridge.proto.workflow_activation.WorkflowActivation) -> temporalio.bridge.proto.workflow_completion.WorkflowActivationCompletion:
        """Handle an activation and return completion.

        This should never raise an exception, but instead catch all exceptions
        and set as completion failure.

        Args:
            act: Protobuf activation.

        Returns:
            Completion object with successful commands set or failure info set.
        """
        ...
    
    @abstractmethod
    def get_serialization_context(self, command_info: Optional[_command_aware_visitor.CommandInfo]) -> Optional[temporalio.converter.SerializationContext]:
        """Return appropriate serialization context.

        Args:
            command_info: Optional information identifying the associated command. If set, the payload
                         codec will have serialization context set appropriately for that command.

        Returns:
            The serialization context, or None if no context should be set.
        """
        ...
    
    def get_thread_id(self) -> Optional[int]:
        """Return the thread identifier that this workflow is running on.

        Not an abstractmethod because it is not mandatory to implement. Used primarily for getting the frames of a deadlocked thread.

        Returns:
            Thread ID if the workflow is running, None if not.
        """
        ...
    


class UnsandboxedWorkflowRunner(WorkflowRunner):
    """Workflow runner that does not do any sandboxing."""
    def prepare_workflow(self, defn: temporalio.workflow._Definition) -> None:
        """Implements :py:meth:`WorkflowRunner.prepare_workflow` as a no-op."""
        ...
    
    def create_instance(self, det: WorkflowInstanceDetails) -> WorkflowInstance:
        """Implements :py:meth:`WorkflowRunner.create_instance`."""
        ...
    


_T = TypeVar("_T")
_Context: TypeAlias = Dict[str, Any]
_ExceptionHandler: TypeAlias = Callable[[asyncio.AbstractEventLoop, _Context], Any]
class _WorkflowInstanceImpl(WorkflowInstance, temporalio.workflow._Runtime, asyncio.AbstractEventLoop):
    def __init__(self, det: WorkflowInstanceDetails) -> None:
        ...
    
    def get_thread_id(self) -> Optional[int]:
        ...
    
    def activate(self, act: temporalio.bridge.proto.workflow_activation.WorkflowActivation) -> temporalio.bridge.proto.workflow_completion.WorkflowActivationCompletion:
        ...
    
    def workflow_all_handlers_finished(self) -> bool:
        ...
    
    def workflow_continue_as_new(self, *args: Any, workflow: Union[None, Callable, str], task_queue: Optional[str], run_timeout: Optional[timedelta], task_timeout: Optional[timedelta], retry_policy: Optional[temporalio.common.RetryPolicy], memo: Optional[Mapping[str, Any]], search_attributes: Optional[Union[temporalio.common.SearchAttributes, temporalio.common.TypedSearchAttributes,]], versioning_intent: Optional[temporalio.workflow.VersioningIntent]) -> NoReturn:
        ...
    
    def workflow_extern_functions(self) -> Mapping[str, Callable]:
        ...
    
    def workflow_get_current_build_id(self) -> str:
        ...
    
    def workflow_get_current_deployment_version(self) -> Optional[temporalio.common.WorkerDeploymentVersion]:
        ...
    
    def workflow_get_current_history_length(self) -> int:
        ...
    
    def workflow_get_current_history_size(self) -> int:
        ...
    
    def workflow_get_external_workflow_handle(self, id: str, *, run_id: Optional[str]) -> temporalio.workflow.ExternalWorkflowHandle[Any]:
        ...
    
    def workflow_get_query_handler(self, name: Optional[str]) -> Optional[Callable]:
        ...
    
    def workflow_get_signal_handler(self, name: Optional[str]) -> Optional[Callable]:
        ...
    
    def workflow_get_update_handler(self, name: Optional[str]) -> Optional[Callable]:
        ...
    
    def workflow_get_update_validator(self, name: Optional[str]) -> Optional[Callable]:
        ...
    
    def workflow_info(self) -> temporalio.workflow.Info:
        ...
    
    def workflow_instance(self) -> Any:
        ...
    
    def workflow_is_continue_as_new_suggested(self) -> bool:
        ...
    
    def workflow_is_replaying(self) -> bool:
        ...
    
    def workflow_memo(self) -> Mapping[str, Any]:
        ...
    
    def workflow_memo_value(self, key: str, default: Any, *, type_hint: Optional[Type]) -> Any:
        ...
    
    def workflow_upsert_memo(self, updates: Mapping[str, Any]) -> None:
        ...
    
    def workflow_metric_meter(self) -> temporalio.common.MetricMeter:
        ...
    
    def workflow_patch(self, id: str, *, deprecated: bool) -> bool:
        ...
    
    def workflow_payload_converter(self) -> temporalio.converter.PayloadConverter:
        ...
    
    def workflow_random(self) -> random.Random:
        ...
    
    def workflow_set_query_handler(self, name: Optional[str], handler: Optional[Callable]) -> None:
        ...
    
    def workflow_set_signal_handler(self, name: Optional[str], handler: Optional[Callable]) -> None:
        ...
    
    def workflow_set_update_handler(self, name: Optional[str], handler: Optional[Callable], validator: Optional[Callable]) -> None:
        ...
    
    def workflow_start_activity(self, activity: Any, *args: Any, task_queue: Optional[str], result_type: Optional[Type], schedule_to_close_timeout: Optional[timedelta], schedule_to_start_timeout: Optional[timedelta], start_to_close_timeout: Optional[timedelta], heartbeat_timeout: Optional[timedelta], retry_policy: Optional[temporalio.common.RetryPolicy], cancellation_type: temporalio.workflow.ActivityCancellationType, activity_id: Optional[str], versioning_intent: Optional[temporalio.workflow.VersioningIntent], summary: Optional[str] = ..., priority: temporalio.common.Priority = ...) -> temporalio.workflow.ActivityHandle[Any]:
        ...
    
    async def workflow_start_child_workflow(self, workflow: Any, *args: Any, id: str, task_queue: Optional[str], result_type: Optional[Type], cancellation_type: temporalio.workflow.ChildWorkflowCancellationType, parent_close_policy: temporalio.workflow.ParentClosePolicy, execution_timeout: Optional[timedelta], run_timeout: Optional[timedelta], task_timeout: Optional[timedelta], id_reuse_policy: temporalio.common.WorkflowIDReusePolicy, retry_policy: Optional[temporalio.common.RetryPolicy], cron_schedule: str, memo: Optional[Mapping[str, Any]], search_attributes: Optional[Union[temporalio.common.SearchAttributes, temporalio.common.TypedSearchAttributes,]], versioning_intent: Optional[temporalio.workflow.VersioningIntent], static_summary: Optional[str] = ..., static_details: Optional[str] = ..., priority: temporalio.common.Priority = ...) -> temporalio.workflow.ChildWorkflowHandle[Any, Any]:
        ...
    
    def workflow_start_local_activity(self, activity: Any, *args: Any, result_type: Optional[Type], schedule_to_close_timeout: Optional[timedelta], schedule_to_start_timeout: Optional[timedelta], start_to_close_timeout: Optional[timedelta], retry_policy: Optional[temporalio.common.RetryPolicy], local_retry_threshold: Optional[timedelta], cancellation_type: temporalio.workflow.ActivityCancellationType, activity_id: Optional[str], summary: Optional[str]) -> temporalio.workflow.ActivityHandle[Any]:
        ...
    
    async def workflow_start_nexus_operation(self, endpoint: str, service: str, operation: nexusrpc.Operation[InputT, OutputT] | str | Callable[..., Any], input: Any, output_type: Type[OutputT] | None, schedule_to_close_timeout: timedelta | None, cancellation_type: temporalio.workflow.NexusOperationCancellationType, headers: Mapping[str, str] | None, summary: str | None) -> temporalio.workflow.NexusOperationHandle[OutputT]:
        ...
    
    def workflow_time_ns(self) -> int:
        ...
    
    def workflow_upsert_search_attributes(self, attributes: Union[temporalio.common.SearchAttributes, Sequence[temporalio.common.SearchAttributeUpdate],]) -> None:
        ...
    
    async def workflow_sleep(self, duration: float, *, summary: Optional[str] = ...) -> None:
        ...
    
    async def workflow_wait_condition(self, fn: Callable[[], bool], *, timeout: Optional[float] = ..., timeout_summary: Optional[str] = ...) -> None:
        ...
    
    def workflow_get_current_details(self) -> str:
        ...
    
    def workflow_set_current_details(self, details: str): # -> None:
        ...
    
    def workflow_is_failure_exception(self, err: BaseException) -> bool:
        ...
    
    def workflow_has_last_completion_result(self) -> bool:
        ...
    
    def workflow_last_completion_result(self, type_hint: Optional[Type]) -> Optional[Any]:
        ...
    
    def workflow_last_failure(self) -> Optional[BaseException]:
        ...
    
    def get_serialization_context(self, command_info: Optional[_command_aware_visitor.CommandInfo]) -> Optional[temporalio.converter.SerializationContext]:
        ...
    
    _Ts = TypeVarTuple("_Ts")
    def call_soon(self, callback: Callable[[Unpack[_Ts]], object], *args: Unpack[_Ts], context: Optional[contextvars.Context] = ...) -> asyncio.Handle:
        ...
    
    def call_later(self, delay: float, callback: Callable[[Unpack[_Ts]], object], *args: Unpack[_Ts], context: Optional[contextvars.Context] = ...) -> asyncio.TimerHandle:
        ...
    
    def call_at(self, when: float, callback: Callable[[Unpack[_Ts]], object], *args: Unpack[_Ts], context: Optional[contextvars.Context] = ...) -> asyncio.TimerHandle:
        ...
    
    def time(self) -> float:
        ...
    
    def create_future(self) -> asyncio.Future[Any]:
        ...
    
    def create_task(self, coro: Union[Awaitable[_T], Generator[Any, None, _T]], *, name: Optional[str] = ..., context: Optional[contextvars.Context] = ...) -> asyncio.Task[_T]:
        ...
    
    def get_exception_handler(self) -> Optional[_ExceptionHandler]:
        ...
    
    def get_task_factory(self) -> None:
        ...
    
    def set_exception_handler(self, handler: Optional[_ExceptionHandler]) -> None:
        ...
    
    def default_exception_handler(self, context: _Context) -> None:
        ...
    
    def call_exception_handler(self, context: _Context) -> None:
        ...
    
    def get_debug(self) -> bool:
        ...
    


class _WorkflowInboundImpl(WorkflowInboundInterceptor):
    def __init__(self, instance: _WorkflowInstanceImpl) -> None:
        ...
    
    def init(self, outbound: WorkflowOutboundInterceptor) -> None:
        ...
    
    async def execute_workflow(self, input: ExecuteWorkflowInput) -> Any:
        ...
    
    async def handle_signal(self, input: HandleSignalInput) -> None:
        ...
    
    async def handle_query(self, input: HandleQueryInput) -> Any:
        ...
    
    def handle_update_validator(self, input: HandleUpdateInput) -> None:
        ...
    
    async def handle_update_handler(self, input: HandleUpdateInput) -> Any:
        ...
    


class _WorkflowOutboundImpl(WorkflowOutboundInterceptor):
    def __init__(self, instance: _WorkflowInstanceImpl) -> None:
        ...
    
    def continue_as_new(self, input: ContinueAsNewInput) -> NoReturn:
        ...
    
    def info(self) -> temporalio.workflow.Info:
        ...
    
    async def signal_child_workflow(self, input: SignalChildWorkflowInput) -> None:
        ...
    
    async def signal_external_workflow(self, input: SignalExternalWorkflowInput) -> None:
        ...
    
    def start_activity(self, input: StartActivityInput) -> temporalio.workflow.ActivityHandle[Any]:
        ...
    
    async def start_child_workflow(self, input: StartChildWorkflowInput) -> temporalio.workflow.ChildWorkflowHandle[Any, Any]:
        ...
    
    async def start_nexus_operation(self, input: StartNexusOperationInput[Any, OutputT]) -> _NexusOperationHandle[OutputT]:
        ...
    
    def start_local_activity(self, input: StartLocalActivityInput) -> temporalio.workflow.ActivityHandle[Any]:
        ...
    


@dataclass(frozen=True)
class _TimerOptions:
    user_metadata: Optional[temporalio.api.sdk.v1.UserMetadata] = ...


_TimerOptionsCtxVar: contextvars.ContextVar[_TimerOptions] = ...
class _TimerHandle(asyncio.TimerHandle):
    def __init__(self, seq: int, when: float, options: Optional[_TimerOptions], callback: Callable[..., Any], args: Sequence[Any], loop: asyncio.AbstractEventLoop, context: Optional[contextvars.Context]) -> None:
        ...
    


class _ActivityDoBackoffError(BaseException):
    def __init__(self, backoff: temporalio.bridge.proto.activity_result.DoBackoff) -> None:
        ...
    


class _ActivityHandle(temporalio.workflow.ActivityHandle[Any]):
    def __init__(self, instance: _WorkflowInstanceImpl, input: Union[StartActivityInput, StartLocalActivityInput], fn: Coroutine[Any, Any, Any]) -> None:
        ...
    
    def cancel(self, msg: Optional[Any] = ...) -> bool:
        ...
    


class _ChildWorkflowHandle(temporalio.workflow.ChildWorkflowHandle[Any, Any]):
    def __init__(self, instance: _WorkflowInstanceImpl, seq: int, input: StartChildWorkflowInput, fn: Coroutine[Any, Any, Any]) -> None:
        ...
    
    @property
    def id(self) -> str:
        ...
    
    @property
    def first_execution_run_id(self) -> Optional[str]:
        ...
    
    async def signal(self, signal: Union[str, Callable], arg: Any = ..., *, args: Sequence[Any] = ...) -> None:
        ...
    


class _ExternalWorkflowHandle(temporalio.workflow.ExternalWorkflowHandle[Any]):
    def __init__(self, instance: _WorkflowInstanceImpl, id: str, run_id: Optional[str]) -> None:
        ...
    
    @property
    def id(self) -> str:
        ...
    
    @property
    def run_id(self) -> Optional[str]:
        ...
    
    async def signal(self, signal: Union[str, Callable], arg: Any = ..., *, args: Sequence[Any] = ...) -> None:
        ...
    
    async def cancel(self) -> None:
        ...
    


class _NexusOperationHandle(temporalio.workflow.NexusOperationHandle[OutputT]):
    def __init__(self, instance: _WorkflowInstanceImpl, seq: int, input: StartNexusOperationInput[Any, OutputT], fn: Coroutine[Any, Any, OutputT]) -> None:
        ...
    
    @property
    def operation_token(self) -> Optional[str]:
        ...
    
    def __await__(self) -> Generator[Any, Any, OutputT]:
        ...
    
    def cancel(self) -> bool:
        ...
    


class _ContinueAsNewError(temporalio.workflow.ContinueAsNewError):
    def __init__(self, instance: _WorkflowInstanceImpl, input: ContinueAsNewInput) -> None:
        ...
    


class _WorkflowExternFunctions(TypedDict):
    __temporal_get_metric_meter: Callable[[], temporalio.common.MetricMeter]
    __temporal_assert_local_activity_valid: Callable[[str], None]
    ...


class _ReplaySafeMetricMeter(temporalio.common.MetricMeter):
    def __init__(self, underlying: temporalio.common.MetricMeter) -> None:
        ...
    
    def create_counter(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricCounter:
        ...
    
    def create_histogram(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricHistogram:
        ...
    
    def create_histogram_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricHistogramFloat:
        ...
    
    def create_histogram_timedelta(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricHistogramTimedelta:
        ...
    
    def create_gauge(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricGauge:
        ...
    
    def create_gauge_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> temporalio.common.MetricGaugeFloat:
        ...
    
    def with_additional_attributes(self, additional_attributes: temporalio.common.MetricAttributes) -> temporalio.common.MetricMeter:
        ...
    


_MetricType = TypeVar("_MetricType", bound=temporalio.common.MetricCommon)
class _ReplaySafeMetricCommon(temporalio.common.MetricCommon, Generic[_MetricType]):
    def __init__(self, underlying: _MetricType) -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def description(self) -> Optional[str]:
        ...
    
    @property
    def unit(self) -> Optional[str]:
        ...
    
    def with_additional_attributes(self, additional_attributes: temporalio.common.MetricAttributes) -> Self:
        ...
    


class _ReplaySafeMetricCounter(temporalio.common.MetricCounter, _ReplaySafeMetricCommon[temporalio.common.MetricCounter]):
    def add(self, value: int, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _ReplaySafeMetricHistogram(temporalio.common.MetricHistogram, _ReplaySafeMetricCommon[temporalio.common.MetricHistogram]):
    def record(self, value: int, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _ReplaySafeMetricHistogramFloat(temporalio.common.MetricHistogramFloat, _ReplaySafeMetricCommon[temporalio.common.MetricHistogramFloat]):
    def record(self, value: float, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _ReplaySafeMetricHistogramTimedelta(temporalio.common.MetricHistogramTimedelta, _ReplaySafeMetricCommon[temporalio.common.MetricHistogramTimedelta]):
    def record(self, value: timedelta, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _ReplaySafeMetricGauge(temporalio.common.MetricGauge, _ReplaySafeMetricCommon[temporalio.common.MetricGauge]):
    def set(self, value: int, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _ReplaySafeMetricGaugeFloat(temporalio.common.MetricGaugeFloat, _ReplaySafeMetricCommon[temporalio.common.MetricGaugeFloat]):
    def set(self, value: float, additional_attributes: Optional[temporalio.common.MetricAttributes] = ...) -> None:
        ...
    


class _WorkflowBeingEvictedError(BaseException):
    ...


@dataclass
class HandlerExecution:
    """Information about an execution of a signal or update handler."""
    name: str
    unfinished_policy: temporalio.workflow.HandlerUnfinishedPolicy
    id: Optional[str] = ...


class _WorkflowLogicFlag(IntEnum):
    """Flags that may be set on task/activation completion to differentiate new from old workflow behavior."""
    RAISE_ON_CANCELLING_COMPLETED_ACTIVITY = ...


