"""
This type stub file was generated by pyright.
"""

import grpc
from .request_response_pb2 import AddOrUpdateRemoteClusterRequest, AddOrUpdateRemoteClusterResponse, AddSearchAttributesRequest, AddSearchAttributesResponse, ClusterMetadata, CreateNexusEndpointRequest, CreateNexusEndpointResponse, DeleteNamespaceRequest, DeleteNamespaceResponse, DeleteNexusEndpointRequest, DeleteNexusEndpointResponse, GetNexusEndpointRequest, GetNexusEndpointResponse, ListClustersRequest, ListClustersResponse, ListNexusEndpointsRequest, ListNexusEndpointsResponse, ListSearchAttributesRequest, ListSearchAttributesResponse, RemoveRemoteClusterRequest, RemoveRemoteClusterResponse, RemoveSearchAttributesRequest, RemoveSearchAttributesResponse, UpdateNexusEndpointRequest, UpdateNexusEndpointResponse
from .service_pb2_grpc import OperatorServiceServicer, OperatorServiceStub, add_OperatorServiceServicer_to_server

__all__ = ["AddOrUpdateRemoteClusterRequest", "AddOrUpdateRemoteClusterResponse", "AddSearchAttributesRequest", "AddSearchAttributesResponse", "ClusterMetadata", "CreateNexusEndpointRequest", "CreateNexusEndpointResponse", "DeleteNamespaceRequest", "DeleteNamespaceResponse", "DeleteNexusEndpointRequest", "DeleteNexusEndpointResponse", "GetNexusEndpointRequest", "GetNexusEndpointResponse", "ListClustersRequest", "ListClustersResponse", "ListNexusEndpointsRequest", "ListNexusEndpointsResponse", "ListSearchAttributesRequest", "ListSearchAttributesResponse", "RemoveRemoteClusterRequest", "RemoveRemoteClusterResponse", "RemoveSearchAttributesRequest", "RemoveSearchAttributesResponse", "UpdateNexusEndpointRequest", "UpdateNexusEndpointResponse"]
