"""
This type stub file was generated by pyright.
"""

from .message_pb2 import ClusterReplicationConfig, FailoverStatus, NamespaceReplicationConfig

__all__ = ["ClusterReplicationConfig", "FailoverStatus", "NamespaceReplicationConfig"]
