temporal:
  url: "temporal:7233"
  namespace: default
  task_queue: easyeasm_demo

neo4j:
  password: supertestovaciheslo
  bolt: bolt://neo4j:7687
  user: neo4j

redis:
  host: redis
  port: 6379

nmap:
  targets: ["localhost"]
  arguments: "-sV -A"