temporal:
  url: "temporal:7233"
  namespace: default
  task_queue: easyeasm_demo

neo4j:
  password: supertestovaciheslo
  bolt: bolt://neo4j:7687
  user: neo4j

redis:
  host: redis
  port: 6379

isim:
  url: "http://isim:8000"

nmap_basic:
  targets:
    - metasploitable3
  arguments: "-sV -A"

nmap_topology:
  targets:
    - metasploitable3
  arguments: "-sn -n --traceroute"

scanner:
  domains:
    - vulnweb.com
  wordlist: "wordlist.txt"
