"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _ResourceState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ResourceStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESOURCE_STATE_UNSPECIFIED: _ResourceState.ValueType
    RESOURCE_STATE_ACTIVATING: _ResourceState.ValueType
    RESOURCE_STATE_ACTIVATION_FAILED: _ResourceState.ValueType
    RESOURCE_STATE_ACTIVE: _ResourceState.ValueType
    RESOURCE_STATE_UPDATING: _ResourceState.ValueType
    RESOURCE_STATE_UPDATE_FAILED: _ResourceState.ValueType
    RESOURCE_STATE_DELETING: _ResourceState.ValueType
    RESOURCE_STATE_DELETE_FAILED: _ResourceState.ValueType
    RESOURCE_STATE_DELETED: _ResourceState.ValueType
    RESOURCE_STATE_SUSPENDED: _ResourceState.ValueType
    RESOURCE_STATE_EXPIRED: _ResourceState.ValueType
    ...


class ResourceState(_ResourceState, metaclass=_ResourceStateEnumTypeWrapper):
    ...


RESOURCE_STATE_UNSPECIFIED: ResourceState.ValueType
RESOURCE_STATE_ACTIVATING: ResourceState.ValueType
RESOURCE_STATE_ACTIVATION_FAILED: ResourceState.ValueType
RESOURCE_STATE_ACTIVE: ResourceState.ValueType
RESOURCE_STATE_UPDATING: ResourceState.ValueType
RESOURCE_STATE_UPDATE_FAILED: ResourceState.ValueType
RESOURCE_STATE_DELETING: ResourceState.ValueType
RESOURCE_STATE_DELETE_FAILED: ResourceState.ValueType
RESOURCE_STATE_DELETED: ResourceState.ValueType
RESOURCE_STATE_SUSPENDED: ResourceState.ValueType
RESOURCE_STATE_EXPIRED: ResourceState.ValueType
global___ResourceState = ResourceState
