"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _BatchOperationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _BatchOperationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BatchOperationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BATCH_OPERATION_TYPE_UNSPECIFIED: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_TERMINATE: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_CANCEL: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_SIGNAL: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_DELETE: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_RESET: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_UPDATE_EXECUTION_OPTIONS: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_UNPAUSE_ACTIVITY: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_UPDATE_ACTIVITY_OPTIONS: _BatchOperationType.ValueType
    BATCH_OPERATION_TYPE_RESET_ACTIVITY: _BatchOperationType.ValueType
    ...


class BatchOperationType(_BatchOperationType, metaclass=_BatchOperationTypeEnumTypeWrapper):
    ...


BATCH_OPERATION_TYPE_UNSPECIFIED: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_TERMINATE: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_CANCEL: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_SIGNAL: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_DELETE: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_RESET: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_UPDATE_EXECUTION_OPTIONS: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_UNPAUSE_ACTIVITY: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_UPDATE_ACTIVITY_OPTIONS: BatchOperationType.ValueType
BATCH_OPERATION_TYPE_RESET_ACTIVITY: BatchOperationType.ValueType
global___BatchOperationType = BatchOperationType
class _BatchOperationState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _BatchOperationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BatchOperationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BATCH_OPERATION_STATE_UNSPECIFIED: _BatchOperationState.ValueType
    BATCH_OPERATION_STATE_RUNNING: _BatchOperationState.ValueType
    BATCH_OPERATION_STATE_COMPLETED: _BatchOperationState.ValueType
    BATCH_OPERATION_STATE_FAILED: _BatchOperationState.ValueType
    ...


class BatchOperationState(_BatchOperationState, metaclass=_BatchOperationStateEnumTypeWrapper):
    ...


BATCH_OPERATION_STATE_UNSPECIFIED: BatchOperationState.ValueType
BATCH_OPERATION_STATE_RUNNING: BatchOperationState.ValueType
BATCH_OPERATION_STATE_COMPLETED: BatchOperationState.ValueType
BATCH_OPERATION_STATE_FAILED: BatchOperationState.ValueType
global___BatchOperationState = BatchOperationState
