"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _EncodingType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _EncodingTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EncodingType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENCODING_TYPE_UNSPECIFIED: _EncodingType.ValueType
    ENCODING_TYPE_PROTO3: _EncodingType.ValueType
    ENCODING_TYPE_JSON: _EncodingType.ValueType
    ...


class EncodingType(_EncodingType, metaclass=_EncodingTypeEnumTypeWrapper):
    ...


ENCODING_TYPE_UNSPECIFIED: EncodingType.ValueType
ENCODING_TYPE_PROTO3: EncodingType.ValueType
ENCODING_TYPE_JSON: EncodingType.ValueType
global___EncodingType = EncodingType
class _IndexedValueType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _IndexedValueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IndexedValueType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    INDEXED_VALUE_TYPE_UNSPECIFIED: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_TEXT: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_KEYWORD: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_INT: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_DOUBLE: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_BOOL: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_DATETIME: _IndexedValueType.ValueType
    INDEXED_VALUE_TYPE_KEYWORD_LIST: _IndexedValueType.ValueType
    ...


class IndexedValueType(_IndexedValueType, metaclass=_IndexedValueTypeEnumTypeWrapper):
    ...


INDEXED_VALUE_TYPE_UNSPECIFIED: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_TEXT: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_KEYWORD: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_INT: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_DOUBLE: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_BOOL: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_DATETIME: IndexedValueType.ValueType
INDEXED_VALUE_TYPE_KEYWORD_LIST: IndexedValueType.ValueType
global___IndexedValueType = IndexedValueType
class _Severity:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _SeverityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Severity.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SEVERITY_UNSPECIFIED: _Severity.ValueType
    SEVERITY_HIGH: _Severity.ValueType
    SEVERITY_MEDIUM: _Severity.ValueType
    SEVERITY_LOW: _Severity.ValueType
    ...


class Severity(_Severity, metaclass=_SeverityEnumTypeWrapper):
    ...


SEVERITY_UNSPECIFIED: Severity.ValueType
SEVERITY_HIGH: Severity.ValueType
SEVERITY_MEDIUM: Severity.ValueType
SEVERITY_LOW: Severity.ValueType
global___Severity = Severity
class _CallbackState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _CallbackStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CallbackState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CALLBACK_STATE_UNSPECIFIED: _CallbackState.ValueType
    CALLBACK_STATE_STANDBY: _CallbackState.ValueType
    CALLBACK_STATE_SCHEDULED: _CallbackState.ValueType
    CALLBACK_STATE_BACKING_OFF: _CallbackState.ValueType
    CALLBACK_STATE_FAILED: _CallbackState.ValueType
    CALLBACK_STATE_SUCCEEDED: _CallbackState.ValueType
    CALLBACK_STATE_BLOCKED: _CallbackState.ValueType
    ...


class CallbackState(_CallbackState, metaclass=_CallbackStateEnumTypeWrapper):
    """State of a callback."""
    ...


CALLBACK_STATE_UNSPECIFIED: CallbackState.ValueType
CALLBACK_STATE_STANDBY: CallbackState.ValueType
CALLBACK_STATE_SCHEDULED: CallbackState.ValueType
CALLBACK_STATE_BACKING_OFF: CallbackState.ValueType
CALLBACK_STATE_FAILED: CallbackState.ValueType
CALLBACK_STATE_SUCCEEDED: CallbackState.ValueType
CALLBACK_STATE_BLOCKED: CallbackState.ValueType
global___CallbackState = CallbackState
class _PendingNexusOperationState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _PendingNexusOperationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingNexusOperationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PENDING_NEXUS_OPERATION_STATE_UNSPECIFIED: _PendingNexusOperationState.ValueType
    PENDING_NEXUS_OPERATION_STATE_SCHEDULED: _PendingNexusOperationState.ValueType
    PENDING_NEXUS_OPERATION_STATE_BACKING_OFF: _PendingNexusOperationState.ValueType
    PENDING_NEXUS_OPERATION_STATE_STARTED: _PendingNexusOperationState.ValueType
    PENDING_NEXUS_OPERATION_STATE_BLOCKED: _PendingNexusOperationState.ValueType
    ...


class PendingNexusOperationState(_PendingNexusOperationState, metaclass=_PendingNexusOperationStateEnumTypeWrapper):
    """State of a pending Nexus operation."""
    ...


PENDING_NEXUS_OPERATION_STATE_UNSPECIFIED: PendingNexusOperationState.ValueType
PENDING_NEXUS_OPERATION_STATE_SCHEDULED: PendingNexusOperationState.ValueType
PENDING_NEXUS_OPERATION_STATE_BACKING_OFF: PendingNexusOperationState.ValueType
PENDING_NEXUS_OPERATION_STATE_STARTED: PendingNexusOperationState.ValueType
PENDING_NEXUS_OPERATION_STATE_BLOCKED: PendingNexusOperationState.ValueType
global___PendingNexusOperationState = PendingNexusOperationState
class _NexusOperationCancellationState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _NexusOperationCancellationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NexusOperationCancellationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_FAILED: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT: _NexusOperationCancellationState.ValueType
    NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED: _NexusOperationCancellationState.ValueType
    ...


class NexusOperationCancellationState(_NexusOperationCancellationState, metaclass=_NexusOperationCancellationStateEnumTypeWrapper):
    """State of a Nexus operation cancellation."""
    ...


NEXUS_OPERATION_CANCELLATION_STATE_UNSPECIFIED: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_SCHEDULED: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_BACKING_OFF: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_SUCCEEDED: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_FAILED: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_TIMED_OUT: NexusOperationCancellationState.ValueType
NEXUS_OPERATION_CANCELLATION_STATE_BLOCKED: NexusOperationCancellationState.ValueType
global___NexusOperationCancellationState = NexusOperationCancellationState
class _WorkflowRuleActionScope:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkflowRuleActionScopeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowRuleActionScope.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKFLOW_RULE_ACTION_SCOPE_UNSPECIFIED: _WorkflowRuleActionScope.ValueType
    WORKFLOW_RULE_ACTION_SCOPE_WORKFLOW: _WorkflowRuleActionScope.ValueType
    WORKFLOW_RULE_ACTION_SCOPE_ACTIVITY: _WorkflowRuleActionScope.ValueType
    ...


class WorkflowRuleActionScope(_WorkflowRuleActionScope, metaclass=_WorkflowRuleActionScopeEnumTypeWrapper):
    ...


WORKFLOW_RULE_ACTION_SCOPE_UNSPECIFIED: WorkflowRuleActionScope.ValueType
WORKFLOW_RULE_ACTION_SCOPE_WORKFLOW: WorkflowRuleActionScope.ValueType
WORKFLOW_RULE_ACTION_SCOPE_ACTIVITY: WorkflowRuleActionScope.ValueType
global___WorkflowRuleActionScope = WorkflowRuleActionScope
class _ApplicationErrorCategory:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ApplicationErrorCategoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ApplicationErrorCategory.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    APPLICATION_ERROR_CATEGORY_UNSPECIFIED: _ApplicationErrorCategory.ValueType
    APPLICATION_ERROR_CATEGORY_BENIGN: _ApplicationErrorCategory.ValueType
    ...


class ApplicationErrorCategory(_ApplicationErrorCategory, metaclass=_ApplicationErrorCategoryEnumTypeWrapper):
    ...


APPLICATION_ERROR_CATEGORY_UNSPECIFIED: ApplicationErrorCategory.ValueType
APPLICATION_ERROR_CATEGORY_BENIGN: ApplicationErrorCategory.ValueType
global___ApplicationErrorCategory = ApplicationErrorCategory
class _WorkerStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkerStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkerStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKER_STATUS_UNSPECIFIED: _WorkerStatus.ValueType
    WORKER_STATUS_RUNNING: _WorkerStatus.ValueType
    WORKER_STATUS_SHUTTING_DOWN: _WorkerStatus.ValueType
    WORKER_STATUS_SHUTDOWN: _WorkerStatus.ValueType
    ...


class WorkerStatus(_WorkerStatus, metaclass=_WorkerStatusEnumTypeWrapper):
    """(-- api-linter: core::0216::synonyms=disabled
    aip.dev/not-precedent: It seems we have both state and status, and status is a better fit for workers. --)
    """
    ...


WORKER_STATUS_UNSPECIFIED: WorkerStatus.ValueType
WORKER_STATUS_RUNNING: WorkerStatus.ValueType
WORKER_STATUS_SHUTTING_DOWN: WorkerStatus.ValueType
WORKER_STATUS_SHUTDOWN: WorkerStatus.ValueType
global___WorkerStatus = WorkerStatus
