"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _CommandType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _CommandTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_CommandType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COMMAND_TYPE_UNSPECIFIED: _CommandType.ValueType
    COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK: _CommandType.ValueType
    COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK: _CommandType.ValueType
    COMMAND_TYPE_START_TIMER: _CommandType.ValueType
    COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_CANCEL_TIMER: _CommandType.ValueType
    COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_RECORD_MARKER: _CommandType.ValueType
    COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION: _CommandType.ValueType
    COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES: _CommandType.ValueType
    COMMAND_TYPE_PROTOCOL_MESSAGE: _CommandType.ValueType
    COMMAND_TYPE_MODIFY_WORKFLOW_PROPERTIES: _CommandType.ValueType
    COMMAND_TYPE_SCHEDULE_NEXUS_OPERATION: _CommandType.ValueType
    COMMAND_TYPE_REQUEST_CANCEL_NEXUS_OPERATION: _CommandType.ValueType
    ...


class CommandType(_CommandType, metaclass=_CommandTypeEnumTypeWrapper):
    """Whenever this list of command types is changed do change the function shouldBufferEvent in mutableStateBuilder.go to make sure to do the correct event ordering."""
    ...


COMMAND_TYPE_UNSPECIFIED: CommandType.ValueType
COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK: CommandType.ValueType
COMMAND_TYPE_REQUEST_CANCEL_ACTIVITY_TASK: CommandType.ValueType
COMMAND_TYPE_START_TIMER: CommandType.ValueType
COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_CANCEL_TIMER: CommandType.ValueType
COMMAND_TYPE_CANCEL_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_RECORD_MARKER: CommandType.ValueType
COMMAND_TYPE_CONTINUE_AS_NEW_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_START_CHILD_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_SIGNAL_EXTERNAL_WORKFLOW_EXECUTION: CommandType.ValueType
COMMAND_TYPE_UPSERT_WORKFLOW_SEARCH_ATTRIBUTES: CommandType.ValueType
COMMAND_TYPE_PROTOCOL_MESSAGE: CommandType.ValueType
COMMAND_TYPE_MODIFY_WORKFLOW_PROPERTIES: CommandType.ValueType
COMMAND_TYPE_SCHEDULE_NEXUS_OPERATION: CommandType.ValueType
COMMAND_TYPE_REQUEST_CANCEL_NEXUS_OPERATION: CommandType.ValueType
global___CommandType = CommandType
