"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _DeploymentReachability:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _DeploymentReachabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DeploymentReachability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DEPLOYMENT_REACHABILITY_UNSPECIFIED: _DeploymentReachability.ValueType
    DEPLOYMENT_REACHABILITY_REACHABLE: _DeploymentReachability.ValueType
    DEPLOYMENT_REACHABILITY_CLOSED_WORKFLOWS_ONLY: _DeploymentReachability.ValueType
    DEPLOYMENT_REACHABILITY_UNREACHABLE: _DeploymentReachability.ValueType
    ...


class DeploymentReachability(_DeploymentReachability, metaclass=_DeploymentReachabilityEnumTypeWrapper):
    """Specify the reachability level for a deployment so users can decide if it is time to
    decommission the deployment.
    """
    ...


DEPLOYMENT_REACHABILITY_UNSPECIFIED: DeploymentReachability.ValueType
DEPLOYMENT_REACHABILITY_REACHABLE: DeploymentReachability.ValueType
DEPLOYMENT_REACHABILITY_CLOSED_WORKFLOWS_ONLY: DeploymentReachability.ValueType
DEPLOYMENT_REACHABILITY_UNREACHABLE: DeploymentReachability.ValueType
global___DeploymentReachability = DeploymentReachability
class _VersionDrainageStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _VersionDrainageStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VersionDrainageStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VERSION_DRAINAGE_STATUS_UNSPECIFIED: _VersionDrainageStatus.ValueType
    VERSION_DRAINAGE_STATUS_DRAINING: _VersionDrainageStatus.ValueType
    VERSION_DRAINAGE_STATUS_DRAINED: _VersionDrainageStatus.ValueType
    ...


class VersionDrainageStatus(_VersionDrainageStatus, metaclass=_VersionDrainageStatusEnumTypeWrapper):
    """(-- api-linter: core::0216::synonyms=disabled
        aip.dev/not-precedent: Call this status because it is . --)
    Specify the drainage status for a Worker Deployment Version so users can decide whether they
    can safely decommission the version.
    Experimental. Worker Deployments are experimental and might significantly change in the future.
    """
    ...


VERSION_DRAINAGE_STATUS_UNSPECIFIED: VersionDrainageStatus.ValueType
VERSION_DRAINAGE_STATUS_DRAINING: VersionDrainageStatus.ValueType
VERSION_DRAINAGE_STATUS_DRAINED: VersionDrainageStatus.ValueType
global___VersionDrainageStatus = VersionDrainageStatus
class _WorkerVersioningMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkerVersioningModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkerVersioningMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKER_VERSIONING_MODE_UNSPECIFIED: _WorkerVersioningMode.ValueType
    WORKER_VERSIONING_MODE_UNVERSIONED: _WorkerVersioningMode.ValueType
    WORKER_VERSIONING_MODE_VERSIONED: _WorkerVersioningMode.ValueType
    ...


class WorkerVersioningMode(_WorkerVersioningMode, metaclass=_WorkerVersioningModeEnumTypeWrapper):
    """Versioning Mode of a worker is set by the app developer in the worker code, and specifies the
    behavior of the system in the following related aspects:
    - Whether or not Temporal Server considers this worker's version (Build ID) when dispatching
      tasks to it.
    - Whether or not the workflows processed by this worker are versioned using the worker's version.
    Experimental. Worker Deployments are experimental and might significantly change in the future.
    """
    ...


WORKER_VERSIONING_MODE_UNSPECIFIED: WorkerVersioningMode.ValueType
WORKER_VERSIONING_MODE_UNVERSIONED: WorkerVersioningMode.ValueType
WORKER_VERSIONING_MODE_VERSIONED: WorkerVersioningMode.ValueType
global___WorkerVersioningMode = WorkerVersioningMode
class _WorkerDeploymentVersionStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkerDeploymentVersionStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkerDeploymentVersionStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKER_DEPLOYMENT_VERSION_STATUS_UNSPECIFIED: _WorkerDeploymentVersionStatus.ValueType
    WORKER_DEPLOYMENT_VERSION_STATUS_INACTIVE: _WorkerDeploymentVersionStatus.ValueType
    WORKER_DEPLOYMENT_VERSION_STATUS_CURRENT: _WorkerDeploymentVersionStatus.ValueType
    WORKER_DEPLOYMENT_VERSION_STATUS_RAMPING: _WorkerDeploymentVersionStatus.ValueType
    WORKER_DEPLOYMENT_VERSION_STATUS_DRAINING: _WorkerDeploymentVersionStatus.ValueType
    WORKER_DEPLOYMENT_VERSION_STATUS_DRAINED: _WorkerDeploymentVersionStatus.ValueType
    ...


class WorkerDeploymentVersionStatus(_WorkerDeploymentVersionStatus, metaclass=_WorkerDeploymentVersionStatusEnumTypeWrapper):
    """(-- api-linter: core::0216::synonyms=disabled
        aip.dev/not-precedent: Call this status because it is . --)
    Specify the status of a Worker Deployment Version.
    Experimental. Worker Deployments are experimental and might significantly change in the future.
    """
    ...


WORKER_DEPLOYMENT_VERSION_STATUS_UNSPECIFIED: WorkerDeploymentVersionStatus.ValueType
WORKER_DEPLOYMENT_VERSION_STATUS_INACTIVE: WorkerDeploymentVersionStatus.ValueType
WORKER_DEPLOYMENT_VERSION_STATUS_CURRENT: WorkerDeploymentVersionStatus.ValueType
WORKER_DEPLOYMENT_VERSION_STATUS_RAMPING: WorkerDeploymentVersionStatus.ValueType
WORKER_DEPLOYMENT_VERSION_STATUS_DRAINING: WorkerDeploymentVersionStatus.ValueType
WORKER_DEPLOYMENT_VERSION_STATUS_DRAINED: WorkerDeploymentVersionStatus.ValueType
global___WorkerDeploymentVersionStatus = WorkerDeploymentVersionStatus
