"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _NamespaceState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _NamespaceStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_NamespaceState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NAMESPACE_STATE_UNSPECIFIED: _NamespaceState.ValueType
    NAMESPACE_STATE_REGISTERED: _NamespaceState.ValueType
    NAMESPACE_STATE_DEPRECATED: _NamespaceState.ValueType
    NAMESPACE_STATE_DELETED: _NamespaceState.ValueType
    ...


class NamespaceState(_NamespaceState, metaclass=_NamespaceStateEnumTypeWrapper):
    ...


NAMESPACE_STATE_UNSPECIFIED: NamespaceState.ValueType
NAMESPACE_STATE_REGISTERED: NamespaceState.ValueType
NAMESPACE_STATE_DEPRECATED: NamespaceState.ValueType
NAMESPACE_STATE_DELETED: NamespaceState.ValueType
global___NamespaceState = NamespaceState
class _ArchivalState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ArchivalStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ArchivalState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ARCHIVAL_STATE_UNSPECIFIED: _ArchivalState.ValueType
    ARCHIVAL_STATE_DISABLED: _ArchivalState.ValueType
    ARCHIVAL_STATE_ENABLED: _ArchivalState.ValueType
    ...


class ArchivalState(_ArchivalState, metaclass=_ArchivalStateEnumTypeWrapper):
    ...


ARCHIVAL_STATE_UNSPECIFIED: ArchivalState.ValueType
ARCHIVAL_STATE_DISABLED: ArchivalState.ValueType
ARCHIVAL_STATE_ENABLED: ArchivalState.ValueType
global___ArchivalState = ArchivalState
class _ReplicationState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ReplicationStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ReplicationState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    REPLICATION_STATE_UNSPECIFIED: _ReplicationState.ValueType
    REPLICATION_STATE_NORMAL: _ReplicationState.ValueType
    REPLICATION_STATE_HANDOVER: _ReplicationState.ValueType
    ...


class ReplicationState(_ReplicationState, metaclass=_ReplicationStateEnumTypeWrapper):
    ...


REPLICATION_STATE_UNSPECIFIED: ReplicationState.ValueType
REPLICATION_STATE_NORMAL: ReplicationState.ValueType
REPLICATION_STATE_HANDOVER: ReplicationState.ValueType
global___ReplicationState = ReplicationState
