"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _ResetReapplyExcludeType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ResetReapplyExcludeTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResetReapplyExcludeType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESET_REAPPLY_EXCLUDE_TYPE_UNSPECIFIED: _ResetReapplyExcludeType.ValueType
    RESET_REAPPLY_EXCLUDE_TYPE_SIGNAL: _ResetReapplyExcludeType.ValueType
    RESET_REAPPLY_EXCLUDE_TYPE_UPDATE: _ResetReapplyExcludeType.ValueType
    RESET_REAPPLY_EXCLUDE_TYPE_NEXUS: _ResetReapplyExcludeType.ValueType
    RESET_REAPPLY_EXCLUDE_TYPE_CANCEL_REQUEST: _ResetReapplyExcludeType.ValueType
    ...


class ResetReapplyExcludeType(_ResetReapplyExcludeType, metaclass=_ResetReapplyExcludeTypeEnumTypeWrapper):
    """Event types to exclude when reapplying events beyond the reset point."""
    ...


RESET_REAPPLY_EXCLUDE_TYPE_UNSPECIFIED: ResetReapplyExcludeType.ValueType
RESET_REAPPLY_EXCLUDE_TYPE_SIGNAL: ResetReapplyExcludeType.ValueType
RESET_REAPPLY_EXCLUDE_TYPE_UPDATE: ResetReapplyExcludeType.ValueType
RESET_REAPPLY_EXCLUDE_TYPE_NEXUS: ResetReapplyExcludeType.ValueType
RESET_REAPPLY_EXCLUDE_TYPE_CANCEL_REQUEST: ResetReapplyExcludeType.ValueType
global___ResetReapplyExcludeType = ResetReapplyExcludeType
class _ResetReapplyType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ResetReapplyTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResetReapplyType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESET_REAPPLY_TYPE_UNSPECIFIED: _ResetReapplyType.ValueType
    RESET_REAPPLY_TYPE_SIGNAL: _ResetReapplyType.ValueType
    RESET_REAPPLY_TYPE_NONE: _ResetReapplyType.ValueType
    RESET_REAPPLY_TYPE_ALL_ELIGIBLE: _ResetReapplyType.ValueType
    ...


class ResetReapplyType(_ResetReapplyType, metaclass=_ResetReapplyTypeEnumTypeWrapper):
    """Deprecated: applications should use ResetReapplyExcludeType to specify
    exclusions from this set, and new event types should be added to ResetReapplyExcludeType
    instead of here.
    """
    ...


RESET_REAPPLY_TYPE_UNSPECIFIED: ResetReapplyType.ValueType
RESET_REAPPLY_TYPE_SIGNAL: ResetReapplyType.ValueType
RESET_REAPPLY_TYPE_NONE: ResetReapplyType.ValueType
RESET_REAPPLY_TYPE_ALL_ELIGIBLE: ResetReapplyType.ValueType
global___ResetReapplyType = ResetReapplyType
class _ResetType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ResetTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResetType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESET_TYPE_UNSPECIFIED: _ResetType.ValueType
    RESET_TYPE_FIRST_WORKFLOW_TASK: _ResetType.ValueType
    RESET_TYPE_LAST_WORKFLOW_TASK: _ResetType.ValueType
    ...


class ResetType(_ResetType, metaclass=_ResetTypeEnumTypeWrapper):
    """Deprecated, see temporalio.api.common.v1.ResetOptions."""
    ...


RESET_TYPE_UNSPECIFIED: ResetType.ValueType
RESET_TYPE_FIRST_WORKFLOW_TASK: ResetType.ValueType
RESET_TYPE_LAST_WORKFLOW_TASK: ResetType.ValueType
global___ResetType = ResetType
