"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _ScheduleOverlapPolicy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ScheduleOverlapPolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ScheduleOverlapPolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCHEDULE_OVERLAP_POLICY_UNSPECIFIED: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_SKIP: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_BUFFER_ONE: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_BUFFER_ALL: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER: _ScheduleOverlapPolicy.ValueType
    SCHEDULE_OVERLAP_POLICY_ALLOW_ALL: _ScheduleOverlapPolicy.ValueType
    ...


class ScheduleOverlapPolicy(_ScheduleOverlapPolicy, metaclass=_ScheduleOverlapPolicyEnumTypeWrapper):
    """ScheduleOverlapPolicy controls what happens when a workflow would be started
    by a schedule, and is already running.
    """
    ...


SCHEDULE_OVERLAP_POLICY_UNSPECIFIED: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_SKIP: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_BUFFER_ONE: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_BUFFER_ALL: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_CANCEL_OTHER: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_TERMINATE_OTHER: ScheduleOverlapPolicy.ValueType
SCHEDULE_OVERLAP_POLICY_ALLOW_ALL: ScheduleOverlapPolicy.ValueType
global___ScheduleOverlapPolicy = ScheduleOverlapPolicy
