"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _TaskQueueKind:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _TaskQueueKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskQueueKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TASK_QUEUE_KIND_UNSPECIFIED: _TaskQueueKind.ValueType
    TASK_QUEUE_KIND_NORMAL: _TaskQueueKind.ValueType
    TASK_QUEUE_KIND_STICKY: _TaskQueueKind.ValueType
    ...


class TaskQueueKind(_TaskQueueKind, metaclass=_TaskQueueKindEnumTypeWrapper):
    ...


TASK_QUEUE_KIND_UNSPECIFIED: TaskQueueKind.ValueType
TASK_QUEUE_KIND_NORMAL: TaskQueueKind.ValueType
TASK_QUEUE_KIND_STICKY: TaskQueueKind.ValueType
global___TaskQueueKind = TaskQueueKind
class _TaskQueueType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _TaskQueueTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskQueueType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TASK_QUEUE_TYPE_UNSPECIFIED: _TaskQueueType.ValueType
    TASK_QUEUE_TYPE_WORKFLOW: _TaskQueueType.ValueType
    TASK_QUEUE_TYPE_ACTIVITY: _TaskQueueType.ValueType
    TASK_QUEUE_TYPE_NEXUS: _TaskQueueType.ValueType
    ...


class TaskQueueType(_TaskQueueType, metaclass=_TaskQueueTypeEnumTypeWrapper):
    ...


TASK_QUEUE_TYPE_UNSPECIFIED: TaskQueueType.ValueType
TASK_QUEUE_TYPE_WORKFLOW: TaskQueueType.ValueType
TASK_QUEUE_TYPE_ACTIVITY: TaskQueueType.ValueType
TASK_QUEUE_TYPE_NEXUS: TaskQueueType.ValueType
global___TaskQueueType = TaskQueueType
class _TaskReachability:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _TaskReachabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TaskReachability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TASK_REACHABILITY_UNSPECIFIED: _TaskReachability.ValueType
    TASK_REACHABILITY_NEW_WORKFLOWS: _TaskReachability.ValueType
    TASK_REACHABILITY_EXISTING_WORKFLOWS: _TaskReachability.ValueType
    TASK_REACHABILITY_OPEN_WORKFLOWS: _TaskReachability.ValueType
    TASK_REACHABILITY_CLOSED_WORKFLOWS: _TaskReachability.ValueType
    ...


class TaskReachability(_TaskReachability, metaclass=_TaskReachabilityEnumTypeWrapper):
    """Specifies which category of tasks may reach a worker on a versioned task queue.
    Used both in a reachability query and its response.
    Deprecated.
    """
    ...


TASK_REACHABILITY_UNSPECIFIED: TaskReachability.ValueType
TASK_REACHABILITY_NEW_WORKFLOWS: TaskReachability.ValueType
TASK_REACHABILITY_EXISTING_WORKFLOWS: TaskReachability.ValueType
TASK_REACHABILITY_OPEN_WORKFLOWS: TaskReachability.ValueType
TASK_REACHABILITY_CLOSED_WORKFLOWS: TaskReachability.ValueType
global___TaskReachability = TaskReachability
class _BuildIdTaskReachability:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _BuildIdTaskReachabilityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BuildIdTaskReachability.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BUILD_ID_TASK_REACHABILITY_UNSPECIFIED: _BuildIdTaskReachability.ValueType
    BUILD_ID_TASK_REACHABILITY_REACHABLE: _BuildIdTaskReachability.ValueType
    BUILD_ID_TASK_REACHABILITY_CLOSED_WORKFLOWS_ONLY: _BuildIdTaskReachability.ValueType
    BUILD_ID_TASK_REACHABILITY_UNREACHABLE: _BuildIdTaskReachability.ValueType
    ...


class BuildIdTaskReachability(_BuildIdTaskReachability, metaclass=_BuildIdTaskReachabilityEnumTypeWrapper):
    """Specifies which category of tasks may reach a versioned worker of a certain Build ID.

    Task Reachability is eventually consistent; there may be a delay (up to few minutes) until it
    converges to the most accurate value but it is designed in a way to take the more conservative
    side until it converges. For example REACHABLE is more conservative than CLOSED_WORKFLOWS_ONLY.

    Note: future activities who inherit their workflow's Build ID but not its Task Queue will not be
    accounted for reachability as server cannot know if they'll happen as they do not use
    assignment rules of their Task Queue. Same goes for Child Workflows or Continue-As-New Workflows
    who inherit the parent/previous workflow's Build ID but not its Task Queue. In those cases, make
    sure to query reachability for the parent/previous workflow's Task Queue as well.
    """
    ...


BUILD_ID_TASK_REACHABILITY_UNSPECIFIED: BuildIdTaskReachability.ValueType
BUILD_ID_TASK_REACHABILITY_REACHABLE: BuildIdTaskReachability.ValueType
BUILD_ID_TASK_REACHABILITY_CLOSED_WORKFLOWS_ONLY: BuildIdTaskReachability.ValueType
BUILD_ID_TASK_REACHABILITY_UNREACHABLE: BuildIdTaskReachability.ValueType
global___BuildIdTaskReachability = BuildIdTaskReachability
class _DescribeTaskQueueMode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _DescribeTaskQueueModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DescribeTaskQueueMode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DESCRIBE_TASK_QUEUE_MODE_UNSPECIFIED: _DescribeTaskQueueMode.ValueType
    DESCRIBE_TASK_QUEUE_MODE_ENHANCED: _DescribeTaskQueueMode.ValueType
    ...


class DescribeTaskQueueMode(_DescribeTaskQueueMode, metaclass=_DescribeTaskQueueModeEnumTypeWrapper):
    ...


DESCRIBE_TASK_QUEUE_MODE_UNSPECIFIED: DescribeTaskQueueMode.ValueType
DESCRIBE_TASK_QUEUE_MODE_ENHANCED: DescribeTaskQueueMode.ValueType
global___DescribeTaskQueueMode = DescribeTaskQueueMode
class _RateLimitSource:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _RateLimitSourceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RateLimitSource.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RATE_LIMIT_SOURCE_UNSPECIFIED: _RateLimitSource.ValueType
    RATE_LIMIT_SOURCE_API: _RateLimitSource.ValueType
    RATE_LIMIT_SOURCE_WORKER: _RateLimitSource.ValueType
    RATE_LIMIT_SOURCE_SYSTEM: _RateLimitSource.ValueType
    ...


class RateLimitSource(_RateLimitSource, metaclass=_RateLimitSourceEnumTypeWrapper):
    """Source for the effective rate limit."""
    ...


RATE_LIMIT_SOURCE_UNSPECIFIED: RateLimitSource.ValueType
RATE_LIMIT_SOURCE_API: RateLimitSource.ValueType
RATE_LIMIT_SOURCE_WORKER: RateLimitSource.ValueType
RATE_LIMIT_SOURCE_SYSTEM: RateLimitSource.ValueType
global___RateLimitSource = RateLimitSource
