"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _UpdateWorkflowExecutionLifecycleStage:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _UpdateWorkflowExecutionLifecycleStageEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UpdateWorkflowExecutionLifecycleStage.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_UNSPECIFIED: _UpdateWorkflowExecutionLifecycleStage.ValueType
    UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ADMITTED: _UpdateWorkflowExecutionLifecycleStage.ValueType
    UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ACCEPTED: _UpdateWorkflowExecutionLifecycleStage.ValueType
    UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED: _UpdateWorkflowExecutionLifecycleStage.ValueType
    ...


class UpdateWorkflowExecutionLifecycleStage(_UpdateWorkflowExecutionLifecycleStage, metaclass=_UpdateWorkflowExecutionLifecycleStageEnumTypeWrapper):
    """UpdateWorkflowExecutionLifecycleStage is specified by clients invoking
    Workflow Updates and used to indicate to the server how long the
    client wishes to wait for a return value from the API. If any value other
    than UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED is sent by the
    client then the API will complete before the Update is finished and will
    return a handle to the running Update so that it can later be polled for
    completion.
    If specified stage wasn't reached before server timeout, server returns
    actual stage reached.
    """
    ...


UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_UNSPECIFIED: UpdateWorkflowExecutionLifecycleStage.ValueType
UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ADMITTED: UpdateWorkflowExecutionLifecycleStage.ValueType
UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_ACCEPTED: UpdateWorkflowExecutionLifecycleStage.ValueType
UPDATE_WORKFLOW_EXECUTION_LIFECYCLE_STAGE_COMPLETED: UpdateWorkflowExecutionLifecycleStage.ValueType
global___UpdateWorkflowExecutionLifecycleStage = UpdateWorkflowExecutionLifecycleStage
class _UpdateAdmittedEventOrigin:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _UpdateAdmittedEventOriginEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_UpdateAdmittedEventOrigin.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UPDATE_ADMITTED_EVENT_ORIGIN_UNSPECIFIED: _UpdateAdmittedEventOrigin.ValueType
    UPDATE_ADMITTED_EVENT_ORIGIN_REAPPLY: _UpdateAdmittedEventOrigin.ValueType
    ...


class UpdateAdmittedEventOrigin(_UpdateAdmittedEventOrigin, metaclass=_UpdateAdmittedEventOriginEnumTypeWrapper):
    """Records why a WorkflowExecutionUpdateAdmittedEvent was written to history.
    Note that not all admitted Updates result in this event.
    """
    ...


UPDATE_ADMITTED_EVENT_ORIGIN_UNSPECIFIED: UpdateAdmittedEventOrigin.ValueType
UPDATE_ADMITTED_EVENT_ORIGIN_REAPPLY: UpdateAdmittedEventOrigin.ValueType
global___UpdateAdmittedEventOrigin = UpdateAdmittedEventOrigin
