"""
This type stub file was generated by pyright.
"""

import builtins
import sys
import typing
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
if sys.version_info >= (3, 10):
    ...
else:
    ...
DESCRIPTOR: google.protobuf.descriptor.FileDescriptor
class _WorkflowIdReusePolicy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkflowIdReusePolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowIdReusePolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED: _WorkflowIdReusePolicy.ValueType
    WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE: _WorkflowIdReusePolicy.ValueType
    WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY: _WorkflowIdReusePolicy.ValueType
    WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE: _WorkflowIdReusePolicy.ValueType
    WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING: _WorkflowIdReusePolicy.ValueType
    ...


class WorkflowIdReusePolicy(_WorkflowIdReusePolicy, metaclass=_WorkflowIdReusePolicyEnumTypeWrapper):
    """Defines whether to allow re-using a workflow id from a previously *closed* workflow.
    If the request is denied, the server returns a `WorkflowExecutionAlreadyStartedFailure` error.

    See `WorkflowIdConflictPolicy` for handling workflow id duplication with a *running* workflow.
    """
    ...


WORKFLOW_ID_REUSE_POLICY_UNSPECIFIED: WorkflowIdReusePolicy.ValueType
WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE: WorkflowIdReusePolicy.ValueType
WORKFLOW_ID_REUSE_POLICY_ALLOW_DUPLICATE_FAILED_ONLY: WorkflowIdReusePolicy.ValueType
WORKFLOW_ID_REUSE_POLICY_REJECT_DUPLICATE: WorkflowIdReusePolicy.ValueType
WORKFLOW_ID_REUSE_POLICY_TERMINATE_IF_RUNNING: WorkflowIdReusePolicy.ValueType
global___WorkflowIdReusePolicy = WorkflowIdReusePolicy
class _WorkflowIdConflictPolicy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkflowIdConflictPolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowIdConflictPolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED: _WorkflowIdConflictPolicy.ValueType
    WORKFLOW_ID_CONFLICT_POLICY_FAIL: _WorkflowIdConflictPolicy.ValueType
    WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING: _WorkflowIdConflictPolicy.ValueType
    WORKFLOW_ID_CONFLICT_POLICY_TERMINATE_EXISTING: _WorkflowIdConflictPolicy.ValueType
    ...


class WorkflowIdConflictPolicy(_WorkflowIdConflictPolicy, metaclass=_WorkflowIdConflictPolicyEnumTypeWrapper):
    """Defines what to do when trying to start a workflow with the same workflow id as a *running* workflow.
    Note that it is *never* valid to have two actively running instances of the same workflow id.

    See `WorkflowIdReusePolicy` for handling workflow id duplication with a *closed* workflow.
    """
    ...


WORKFLOW_ID_CONFLICT_POLICY_UNSPECIFIED: WorkflowIdConflictPolicy.ValueType
WORKFLOW_ID_CONFLICT_POLICY_FAIL: WorkflowIdConflictPolicy.ValueType
WORKFLOW_ID_CONFLICT_POLICY_USE_EXISTING: WorkflowIdConflictPolicy.ValueType
WORKFLOW_ID_CONFLICT_POLICY_TERMINATE_EXISTING: WorkflowIdConflictPolicy.ValueType
global___WorkflowIdConflictPolicy = WorkflowIdConflictPolicy
class _ParentClosePolicy:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ParentClosePolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ParentClosePolicy.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PARENT_CLOSE_POLICY_UNSPECIFIED: _ParentClosePolicy.ValueType
    PARENT_CLOSE_POLICY_TERMINATE: _ParentClosePolicy.ValueType
    PARENT_CLOSE_POLICY_ABANDON: _ParentClosePolicy.ValueType
    PARENT_CLOSE_POLICY_REQUEST_CANCEL: _ParentClosePolicy.ValueType
    ...


class ParentClosePolicy(_ParentClosePolicy, metaclass=_ParentClosePolicyEnumTypeWrapper):
    """Defines how child workflows will react to their parent completing"""
    ...


PARENT_CLOSE_POLICY_UNSPECIFIED: ParentClosePolicy.ValueType
PARENT_CLOSE_POLICY_TERMINATE: ParentClosePolicy.ValueType
PARENT_CLOSE_POLICY_ABANDON: ParentClosePolicy.ValueType
PARENT_CLOSE_POLICY_REQUEST_CANCEL: ParentClosePolicy.ValueType
global___ParentClosePolicy = ParentClosePolicy
class _ContinueAsNewInitiator:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _ContinueAsNewInitiatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ContinueAsNewInitiator.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONTINUE_AS_NEW_INITIATOR_UNSPECIFIED: _ContinueAsNewInitiator.ValueType
    CONTINUE_AS_NEW_INITIATOR_WORKFLOW: _ContinueAsNewInitiator.ValueType
    CONTINUE_AS_NEW_INITIATOR_RETRY: _ContinueAsNewInitiator.ValueType
    CONTINUE_AS_NEW_INITIATOR_CRON_SCHEDULE: _ContinueAsNewInitiator.ValueType
    ...


class ContinueAsNewInitiator(_ContinueAsNewInitiator, metaclass=_ContinueAsNewInitiatorEnumTypeWrapper):
    ...


CONTINUE_AS_NEW_INITIATOR_UNSPECIFIED: ContinueAsNewInitiator.ValueType
CONTINUE_AS_NEW_INITIATOR_WORKFLOW: ContinueAsNewInitiator.ValueType
CONTINUE_AS_NEW_INITIATOR_RETRY: ContinueAsNewInitiator.ValueType
CONTINUE_AS_NEW_INITIATOR_CRON_SCHEDULE: ContinueAsNewInitiator.ValueType
global___ContinueAsNewInitiator = ContinueAsNewInitiator
class _WorkflowExecutionStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _WorkflowExecutionStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_WorkflowExecutionStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    WORKFLOW_EXECUTION_STATUS_UNSPECIFIED: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_RUNNING: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_COMPLETED: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_FAILED: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_CANCELED: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_TERMINATED: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW: _WorkflowExecutionStatus.ValueType
    WORKFLOW_EXECUTION_STATUS_TIMED_OUT: _WorkflowExecutionStatus.ValueType
    ...


class WorkflowExecutionStatus(_WorkflowExecutionStatus, metaclass=_WorkflowExecutionStatusEnumTypeWrapper):
    """(-- api-linter: core::0216::synonyms=disabled
    aip.dev/not-precedent: There is WorkflowExecutionState already in another package. --)
    """
    ...


WORKFLOW_EXECUTION_STATUS_UNSPECIFIED: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_RUNNING: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_COMPLETED: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_FAILED: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_CANCELED: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_TERMINATED: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW: WorkflowExecutionStatus.ValueType
WORKFLOW_EXECUTION_STATUS_TIMED_OUT: WorkflowExecutionStatus.ValueType
global___WorkflowExecutionStatus = WorkflowExecutionStatus
class _PendingActivityState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _PendingActivityStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingActivityState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PENDING_ACTIVITY_STATE_UNSPECIFIED: _PendingActivityState.ValueType
    PENDING_ACTIVITY_STATE_SCHEDULED: _PendingActivityState.ValueType
    PENDING_ACTIVITY_STATE_STARTED: _PendingActivityState.ValueType
    PENDING_ACTIVITY_STATE_CANCEL_REQUESTED: _PendingActivityState.ValueType
    PENDING_ACTIVITY_STATE_PAUSED: _PendingActivityState.ValueType
    PENDING_ACTIVITY_STATE_PAUSE_REQUESTED: _PendingActivityState.ValueType
    ...


class PendingActivityState(_PendingActivityState, metaclass=_PendingActivityStateEnumTypeWrapper):
    ...


PENDING_ACTIVITY_STATE_UNSPECIFIED: PendingActivityState.ValueType
PENDING_ACTIVITY_STATE_SCHEDULED: PendingActivityState.ValueType
PENDING_ACTIVITY_STATE_STARTED: PendingActivityState.ValueType
PENDING_ACTIVITY_STATE_CANCEL_REQUESTED: PendingActivityState.ValueType
PENDING_ACTIVITY_STATE_PAUSED: PendingActivityState.ValueType
PENDING_ACTIVITY_STATE_PAUSE_REQUESTED: PendingActivityState.ValueType
global___PendingActivityState = PendingActivityState
class _PendingWorkflowTaskState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _PendingWorkflowTaskStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PendingWorkflowTaskState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PENDING_WORKFLOW_TASK_STATE_UNSPECIFIED: _PendingWorkflowTaskState.ValueType
    PENDING_WORKFLOW_TASK_STATE_SCHEDULED: _PendingWorkflowTaskState.ValueType
    PENDING_WORKFLOW_TASK_STATE_STARTED: _PendingWorkflowTaskState.ValueType
    ...


class PendingWorkflowTaskState(_PendingWorkflowTaskState, metaclass=_PendingWorkflowTaskStateEnumTypeWrapper):
    ...


PENDING_WORKFLOW_TASK_STATE_UNSPECIFIED: PendingWorkflowTaskState.ValueType
PENDING_WORKFLOW_TASK_STATE_SCHEDULED: PendingWorkflowTaskState.ValueType
PENDING_WORKFLOW_TASK_STATE_STARTED: PendingWorkflowTaskState.ValueType
global___PendingWorkflowTaskState = PendingWorkflowTaskState
class _HistoryEventFilterType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _HistoryEventFilterTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_HistoryEventFilterType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED: _HistoryEventFilterType.ValueType
    HISTORY_EVENT_FILTER_TYPE_ALL_EVENT: _HistoryEventFilterType.ValueType
    HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT: _HistoryEventFilterType.ValueType
    ...


class HistoryEventFilterType(_HistoryEventFilterType, metaclass=_HistoryEventFilterTypeEnumTypeWrapper):
    ...


HISTORY_EVENT_FILTER_TYPE_UNSPECIFIED: HistoryEventFilterType.ValueType
HISTORY_EVENT_FILTER_TYPE_ALL_EVENT: HistoryEventFilterType.ValueType
HISTORY_EVENT_FILTER_TYPE_CLOSE_EVENT: HistoryEventFilterType.ValueType
global___HistoryEventFilterType = HistoryEventFilterType
class _RetryState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _RetryStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_RetryState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RETRY_STATE_UNSPECIFIED: _RetryState.ValueType
    RETRY_STATE_IN_PROGRESS: _RetryState.ValueType
    RETRY_STATE_NON_RETRYABLE_FAILURE: _RetryState.ValueType
    RETRY_STATE_TIMEOUT: _RetryState.ValueType
    RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED: _RetryState.ValueType
    RETRY_STATE_RETRY_POLICY_NOT_SET: _RetryState.ValueType
    RETRY_STATE_INTERNAL_SERVER_ERROR: _RetryState.ValueType
    RETRY_STATE_CANCEL_REQUESTED: _RetryState.ValueType
    ...


class RetryState(_RetryState, metaclass=_RetryStateEnumTypeWrapper):
    ...


RETRY_STATE_UNSPECIFIED: RetryState.ValueType
RETRY_STATE_IN_PROGRESS: RetryState.ValueType
RETRY_STATE_NON_RETRYABLE_FAILURE: RetryState.ValueType
RETRY_STATE_TIMEOUT: RetryState.ValueType
RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED: RetryState.ValueType
RETRY_STATE_RETRY_POLICY_NOT_SET: RetryState.ValueType
RETRY_STATE_INTERNAL_SERVER_ERROR: RetryState.ValueType
RETRY_STATE_CANCEL_REQUESTED: RetryState.ValueType
global___RetryState = RetryState
class _TimeoutType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _TimeoutTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_TimeoutType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    TIMEOUT_TYPE_UNSPECIFIED: _TimeoutType.ValueType
    TIMEOUT_TYPE_START_TO_CLOSE: _TimeoutType.ValueType
    TIMEOUT_TYPE_SCHEDULE_TO_START: _TimeoutType.ValueType
    TIMEOUT_TYPE_SCHEDULE_TO_CLOSE: _TimeoutType.ValueType
    TIMEOUT_TYPE_HEARTBEAT: _TimeoutType.ValueType
    ...


class TimeoutType(_TimeoutType, metaclass=_TimeoutTypeEnumTypeWrapper):
    ...


TIMEOUT_TYPE_UNSPECIFIED: TimeoutType.ValueType
TIMEOUT_TYPE_START_TO_CLOSE: TimeoutType.ValueType
TIMEOUT_TYPE_SCHEDULE_TO_START: TimeoutType.ValueType
TIMEOUT_TYPE_SCHEDULE_TO_CLOSE: TimeoutType.ValueType
TIMEOUT_TYPE_HEARTBEAT: TimeoutType.ValueType
global___TimeoutType = TimeoutType
class _VersioningBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType


class _VersioningBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_VersioningBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    VERSIONING_BEHAVIOR_UNSPECIFIED: _VersioningBehavior.ValueType
    VERSIONING_BEHAVIOR_PINNED: _VersioningBehavior.ValueType
    VERSIONING_BEHAVIOR_AUTO_UPGRADE: _VersioningBehavior.ValueType
    ...


class VersioningBehavior(_VersioningBehavior, metaclass=_VersioningBehaviorEnumTypeWrapper):
    """Versioning Behavior specifies if and how a workflow execution moves between Worker Deployment
    Versions. The Versioning Behavior of a workflow execution is typically specified by the worker
    who completes the first task of the execution, but is also overridable manually for new and
    existing workflows (see VersioningOverride).
    Experimental. Worker Deployments are experimental and might significantly change in the future.
    """
    ...


VERSIONING_BEHAVIOR_UNSPECIFIED: VersioningBehavior.ValueType
VERSIONING_BEHAVIOR_PINNED: VersioningBehavior.ValueType
VERSIONING_BEHAVIOR_AUTO_UPGRADE: VersioningBehavior.ValueType
global___VersioningBehavior = VersioningBehavior
