"""
This type stub file was generated by pyright.
"""

__author__ = ...
__version__ = ...
__last_modification__ = ...
class NmapNotInstalledError(Exception):
    """Exception raised when nmap is not installed"""
    def __init__(self, message=...) -> None:
        ...
    


class NmapXMLParserError(Exception):
    """Exception raised when we can't parse the output"""
    def __init__(self, message=...) -> None:
        ...
    


class NmapExecutionError(Exception):
    """Exception raised when en error occurred during nmap call"""
    ...


