"""
This type stub file was generated by pyright.
"""

class NmapCommandParser:
    """
    Object for parsing the xml results
    
    Each function below will correspond to the parse
    for each nmap command or option.
    """
    def __init__(self, xml_et) -> None:
        ...
    
    def filter_subdomains(self, xmlroot): # -> list[Any]:
        """
        Given the xmlroot return the all the ports that are open from 
        that tree
        """
        ...
    
    def filter_top_ports(self, xmlroot): # -> dict[Any, Any]:
        """
        Given the xmlroot return the all the ports that are open from
        that tree
        """
        ...
    
    def os_identifier_parser(self, xmlroot): # -> dict[Any, Any]:
        """
        Parser for identified os
        """
        ...
    
    def parse_os(self, os_results): # -> list[Any] | dict[Any, Any]:
        """
        parses os results
        """
        ...
    
    def parse_ports(self, xml_hosts): # -> list[Any]:
        """
        Parse parts from xml
        """
        ...
    
    def parse_runtime(self, xml): # -> None:
        """
        Parse parts from xml
        """
        ...
    
    def parse_task_results(self, xml): # -> list[Any]:
        """
        Parse parts from xml
        """
        ...
    
    def parse_mac_address(self, xml): # -> None:
        """
        Parse parts from xml
        """
        ...
    
    def parse_hostnames(self, host): # -> list[Any]:
        """
        Parse parts from xml
        """
        ...
    
    def get_hostname_state(self, xml): # -> None:
        """
        Parse parts from xml
        """
        ...
    
    def parse_scripts(self, scripts_xml): # -> list[Any]:
        ...
    
    def convert_xml_tables(self, xml_tables): # -> dict[Any, Any]:
        ...
    
    def convert_xml_elements(self, xml_obj): # -> dict[Any, Any]:
        ...
    


