"""
This type stub file was generated by pyright.
"""
from os import PathLike
from typing import TypeAlias, Sequence
from xml.etree.ElementTree import Element

from nmap3.utils import user_is_root

__author__ = ...
__version__ = ...
__last_modification__ = ...
OS_TYPE = ...
type CMD_TYPE = str | bytes | PathLike[str] | PathLike[bytes] | Sequence[str | bytes | PathLike[str] | PathLike[bytes]]

class Nmap:
    """
    This nmap class allows us to use the nmap port scanner tool from within python
    by calling nmap3.Nmap()
    """
    def __init__(self, path=...) -> None:
        """
        Module initialization

        :param path: Path where nmap is installed on a user system. On linux system it's typically on /usr/bin/nmap.
        """
        ...
    
    def require_root(self, required=...): # -> None:
        """
        Call this method to add "sudo" in front of nmap call
        """
        ...
    
    def default_command(self) -> str:
        """
        Returns the default nmap command
        that will be chained with all others
        eg nmap -oX -
        """
        ...
    
    def default_command_privileged(self) -> str:
        """
        Commands that require root privileges
        """
        ...
    
    def nmap_version(self): # -> dict[Any, Any]:
        """
        Returns nmap version and build details
        """
        ...
    
    def scan_command(self, target: str, arg: str, args: str | None = None, timeout: float | None = None) -> Element:
        ...
    
    def scan_top_ports(self, target, default=..., args=..., timeout=...): # -> dict[Any, Any]:
        """
        Perform nmap's top ports scan

        :param: target can be IP or domain
        :param: default is the default top port

        This top port requires root previledges
        """
        ...
    
    def nmap_dns_brute_script(self, target, dns_brute=..., args=..., timeout=...): # -> list[Any]:
        """
        Perform nmap scan using the dns-brute script

        :param: target can be IP or domain
        :param: default is the default top port

        nmap -oX - nmmapper.com --script dns-brute.nse
        """
        ...
    
    def nmap_version_detection(self, target, arg=..., args=..., timeout=...): # -> dict[Any, Any]:
        """
        Perform nmap scan using the dns-brute script

        :param: target can be IP or domain

        nmap -oX - nmmapper.com --script dns-brute.nse
        """
        ...
    
    @user_is_root
    def nmap_stealth_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        """
        nmap -oX - nmmapper.com -Pn -sZ
        """
        ...
    
    def nmap_detect_firewall(self, target, arg=..., args=...): # -> None:
        """
        nmap -oX - nmmapper.com -sA
        @ TODO
        """
        ...
    
    @user_is_root
    def nmap_os_detection(self, target, arg=..., args=...): # -> dict[Any, Any]:
        """
        nmap -oX - nmmapper.com -O
        NOTE: Requires root
        """
        ...
    
    def nmap_subnet_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        """
        nmap -oX - nmmapper.com -p-
        NOTE: Requires root
        """
        ...
    
    def nmap_list_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        """
        The list scan is a degenerate form of target discovery that simply lists each target of the network(s)
        specified, without sending any packets to the target targets.

        NOTE: /usr/bin/nmap  -oX  -  192.168.178.1/24  -sL
        """
        ...
    
    def run_command(self, cmd: CMD_TYPE, timeout=...) -> str:
        """
        Runs the nmap command using popen

        @param: cmd--> the command we want run eg /usr/bin/nmap -oX -  nmmapper.com --top-ports 10
        @param: timeout--> command subprocess timeout in seconds.
        """
        ...
    
    def get_xml_et(self, command_output): # -> Element[str]:
        """
        @ return xml ET
        """
        ...
    
    def get_success_xml_et(self, file_name): # -> Element[str]:
        ...
    


class NmapScanTechniques(Nmap):

    def __init__(self, path=...) -> None:
        ...
    
    def scan_command(self, scan_type, target, args, timeout=...): # -> Element[str]:
        ...
    
    @user_is_root
    def nmap_fin_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Perform scan using nmap's fin scan

        @cmd nmap -sF 192.168.178.1

        """
        ...
    
    @user_is_root
    def nmap_syn_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Perform syn scan on this given
        target

        @cmd nmap -sS 192.168.178.1
        """
        ...
    
    def nmap_tcp_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect

        @cmd nmap -sT 192.168.178.1
        """
        ...
    
    @user_is_root
    def nmap_udp_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect

        @cmd nmap -sU 192.168.178.1
        """
        ...
    
    def nmap_ping_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using nmaps' ping scan

        @cmd nmap -sP 192.168.178.1
        """
        ...
    
    def nmap_idle_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Using nmap idle_scan

        @cmd nmap -sL 192.168.178.1
        """
        ...
    
    def nmap_ip_scan(self, target, args=...): # -> dict[Any, Any]:
        """
        Using nmap ip_scan

        @cmd nmap -sO 192.168.178.1
        """
        ...
    


class NmapHostDiscovery(Nmap):
    """
    This object will perform host discovery

    1) Only port scan    (-Pn)
    2) Only host discover    (-sn)
    3) Arp discovery on a local network  (-PR)
    4) Disable DNS resolution    (-n)
    """
    def __init__(self, path=...) -> None:
        ...
    
    def scan_command(self, scan_type, target, args, timeout=...): # -> Element[str]:
        ...
    
    def nmap_portscan_only(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect

        @cmd nmap -Pn 192.168.178.1
        """
        ...
    
    def nmap_no_portscan(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect

        @cmd nmap -sn 192.168.178.1
        """
        ...
    
    def nmap_arp_discovery(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect
        @cmd nmap -PR 192.168.178.1
        """
        ...
    
    def nmap_disable_dns(self, target, args=...): # -> dict[Any, Any]:
        """
        Scan target using the nmap tcp connect
        @cmd nmap -n 192.168.178.1
        """
        ...
    


class NmapAsync(Nmap):
    def __init__(self, path=...) -> None:
        ...
    
    async def run_command(self, cmd, timeout=...) -> str:
        ...
    
    async def scan_command(self, target, arg, args=..., timeout=...): # -> Element[str]:
        ...
    
    async def scan_top_ports(self, target, default=..., args=..., timeout=...): # -> dict[Any, Any]:
        ...
    
    async def nmap_dns_brute_script(self, target, dns_brute=..., args=..., timeout=...): # -> list[Any]:
        ...
    
    async def nmap_version_detection(self, target, arg=..., args=..., timeout=...): # -> dict[Any, Any]:
        ...
    
    async def nmap_stealth_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        ...
    
    async def nmap_os_detection(self, target, arg=..., args=...): # -> dict[Any, Any]:
        ...
    
    async def nmap_subnet_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        ...
    
    async def nmap_list_scan(self, target, arg=..., args=...): # -> dict[Any, Any]:
        ...
    


class NmapScanTechniquesAsync(NmapAsync, NmapScanTechniques):
    def __init__(self, path=...) -> None:
        ...
    
    async def scan_command(self, scan_type, target, args, timeout=...): # -> Element[str]:
        ...
    
    async def nmap_udp_scan(self, target, args=...): # -> dict[Any, Any]:
        ...
    


if __name__ == "__main__":
    parser = ...
    args = ...
    nmap = ...
