temporal:
  url: "localhost:7233"
  namespace: default
  task_queue: easyeasm_demo

neo4j:
  password: supertestovaciheslo
  bolt: bolt://localhost:7687
  user: neo4j

redis:
  host: localhost
  port: 6379

isim:
  url: "http://localhost:8000"

nmap_basic:
  targets:
    - localhost
  arguments: "-sV -A"

nmap_topology:
  targets:
    - localhost
  arguments: "-sn -n --traceroute"

easm_scanner:
  domains:
    - vulnweb.com
  wordlist: "/home/marzival/repos/CASM/temporal/enumeration/subdomainwordlist.txt"
  threads: 100
  mode: fast  # fast or complete