temporal:
  url: localhost:7233
  namespace: default
  task_queue: easyeasm_demo

neo4j:
  password: supertestovaciheslo
  bolt: bolt://localhost:7687
  user: neo4j

redis:
  host: localhost
  port: 6379

isim:
  url: "localhost:8000"

nmap:
  targets: ["localhost"]
  arguments: "-sV -A"