"""
This type stub file was generated by pyright.
"""

from .core_interface_pb2 import ActivityHeartbeat, ActivitySlotInfo, ActivityTaskCompletion, LocalActivitySlotInfo, NexusSlotInfo, WorkflowSlotInfo

__all__ = ["ActivityHeartbeat", "ActivitySlotInfo", "ActivityTaskCompletion", "LocalActivitySlotInfo", "NexusSlotInfo", "WorkflowSlotInfo"]
