"""
This type stub file was generated by pyright.
"""

from .message_pb2 import AWSPrivateLinkInfo, ApiKeyAuthSpec, CertificateFilterSpec, CodecServerSpec, Endpoints, ExportSink, ExportSinkSpec, HighAvailabilitySpec, LifecycleSpec, Limits, MtlsAuthSpec, Namespace, NamespaceRegionStatus, NamespaceSpec, PrivateConnectivity

__all__ = ["AWSPrivateLinkInfo", "ApiKeyAuthSpec", "CertificateFilterSpec", "CodecServerSpec", "Endpoints", "ExportSink", "ExportSinkSpec", "HighAvailabilitySpec", "LifecycleSpec", "Limits", "MtlsAuthSpec", "Namespace", "NamespaceRegionStatus", "NamespaceSpec", "PrivateConnectivity"]
