"""
This type stub file was generated by pyright.
"""

from .workflow_activation_pb2 import CancelWorkflow, DoUpdate, FireTimer, InitializeWorkflow, NotifyHasPatch, QueryWorkflow, RemoveFromCache, ResolveActivity, ResolveChildWorkflowExecution, ResolveChildWorkflowExecutionStart, ResolveChildWorkflowExecutionStartCancelled, ResolveChildWorkflowExecutionStartFailure, ResolveChildWorkflowExecutionStartSuccess, ResolveNexusOperation, ResolveNexusOperationStart, ResolveRequestCancelExternalWorkflow, ResolveSignalExternalWorkflow, SignalWorkflow, UpdateRandomSeed, WorkflowActivation, WorkflowActivationJob

__all__ = ["CancelWorkflow", "DoUpdate", "FireTimer", "InitializeWorkflow", "NotifyHasPatch", "QueryWorkflow", "RemoveFromCache", "ResolveActivity", "ResolveChildWorkflowExecution", "ResolveChildWorkflowExecutionStart", "ResolveChildWorkflowExecutionStartCancelled", "ResolveChildWorkflowExecutionStartFailure", "ResolveChildWorkflowExecutionStartSuccess", "ResolveNexusOperation", "ResolveNexusOperationStart", "ResolveRequestCancelExternalWorkflow", "ResolveSignalExternalWorkflow", "SignalWorkflow", "UpdateRandomSeed", "WorkflowActivation", "WorkflowActivationJob"]
