"""
This type stub file was generated by pyright.
"""

from .activity_task_pb2 import ActivityCancelReason, ActivityCancellationDetails, ActivityTask, Cancel, Start

__all__ = ["ActivityCancelReason", "ActivityCancellationDetails", "ActivityTask", "Cancel", "Start"]
