"""
This type stub file was generated by pyright.
"""

from .message_pb2 import WorkflowRule, WorkflowRuleAction, WorkflowRuleSpec

__all__ = ["WorkflowRule", "WorkflowRuleAction", "WorkflowRuleSpec"]
