"""
This type stub file was generated by pyright.
"""

import types
import temporalio.api.common.v1
import temporalio.types
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timedelta
from enum import IntEnum
from typing import Any, ClassVar, Collection, Generic, Iterator, List, Mapping, Optional, Sequence, Type, TypeVar, Union, overload
from typing_extensions import NamedTuple, Self, TypeAlias

"""Common code used in the Temporal SDK."""
@dataclass
class RetryPolicy:
    """Options for retrying workflows and activities."""
    initial_interval: timedelta = ...
    backoff_coefficient: float = ...
    maximum_interval: Optional[timedelta] = ...
    maximum_attempts: int = ...
    non_retryable_error_types: Optional[Sequence[str]] = ...
    @staticmethod
    def from_proto(proto: temporalio.api.common.v1.RetryPolicy) -> RetryPolicy:
        """Create a retry policy from the proto object."""
        ...
    
    def apply_to_proto(self, proto: temporalio.api.common.v1.RetryPolicy) -> None:
        """Apply the fields in this policy to the given proto object."""
        ...
    


class WorkflowIDReusePolicy(IntEnum):
    """How already-in-use workflow IDs are handled on start.

    See :py:class:`temporalio.api.enums.v1.WorkflowIdReusePolicy`.
    """
    ALLOW_DUPLICATE = ...
    ALLOW_DUPLICATE_FAILED_ONLY = ...
    REJECT_DUPLICATE = ...
    TERMINATE_IF_RUNNING = ...


class WorkflowIDConflictPolicy(IntEnum):
    """How already-running workflows of the same ID are handled on start.

    See :py:class:`temporalio.api.enums.v1.WorkflowIdConflictPolicy`.
    """
    UNSPECIFIED = ...
    FAIL = ...
    USE_EXISTING = ...
    TERMINATE_EXISTING = ...


class QueryRejectCondition(IntEnum):
    """Whether a query should be rejected in certain conditions.

    See :py:class:`temporalio.api.enums.v1.QueryRejectCondition`.
    """
    NONE = ...
    NOT_OPEN = ...
    NOT_COMPLETED_CLEANLY = ...


@dataclass(frozen=True)
class RawValue:
    """Representation of an unconverted, raw payload.

    This type can be used as a parameter or return type in workflows,
    activities, signals, and queries to pass through a raw payload.
    Encoding/decoding of the payload is still done by the system.
    """
    payload: temporalio.api.common.v1.Payload
    def __getstate__(self) -> object:
        """Pickle support."""
        ...
    
    def __setstate__(self, state: object) -> None:
        """Pickle support."""
        ...
    


SearchAttributeValues: TypeAlias = Union[List[str], List[int], List[float], List[bool], List[datetime]]
SearchAttributes: TypeAlias = Mapping[str, SearchAttributeValues]
SearchAttributeValue: TypeAlias = Union[str, int, float, bool, datetime, Sequence[str]]
SearchAttributeValueType = TypeVar("SearchAttributeValueType", str, int, float, bool, datetime, Sequence[str])
class SearchAttributeIndexedValueType(IntEnum):
    """Server index type of a search attribute."""
    TEXT = ...
    KEYWORD = ...
    INT = ...
    DOUBLE = ...
    BOOL = ...
    DATETIME = ...
    KEYWORD_LIST = ...


class SearchAttributeKey(ABC, Generic[SearchAttributeValueType]):
    """Typed search attribute key representation.

    Use one of the ``for`` static methods here to create a key.
    """
    @property
    @abstractmethod
    def name(self) -> str:
        """Get the name of the key."""
        ...
    
    @property
    @abstractmethod
    def indexed_value_type(self) -> SearchAttributeIndexedValueType:
        """Get the server index typed of the key"""
        ...
    
    @property
    @abstractmethod
    def value_type(self) -> Type[SearchAttributeValueType]:
        """Get the Python type of value for the key.

        This may contain generics which cannot be used in ``isinstance``.
        :py:attr:`origin_value_type` can be used instead.
        """
        ...
    
    @property
    def origin_value_type(self) -> Type:
        """Get the Python type of value for the key without generics."""
        ...
    
    def value_set(self, value: SearchAttributeValueType) -> SearchAttributeUpdate[SearchAttributeValueType]:
        """Create a search attribute update to set the given value on this
        key.
        """
        ...
    
    def value_unset(self) -> SearchAttributeUpdate[SearchAttributeValueType]:
        """Create a search attribute update to unset the value on this key."""
        ...
    
    @staticmethod
    def for_text(name: str) -> SearchAttributeKey[str]:
        """Create a 'Text' search attribute type."""
        ...
    
    @staticmethod
    def for_keyword(name: str) -> SearchAttributeKey[str]:
        """Create a 'Keyword' search attribute type."""
        ...
    
    @staticmethod
    def for_int(name: str) -> SearchAttributeKey[int]:
        """Create an 'Int' search attribute type."""
        ...
    
    @staticmethod
    def for_float(name: str) -> SearchAttributeKey[float]:
        """Create a 'Double' search attribute type."""
        ...
    
    @staticmethod
    def for_bool(name: str) -> SearchAttributeKey[bool]:
        """Create a 'Bool' search attribute type."""
        ...
    
    @staticmethod
    def for_datetime(name: str) -> SearchAttributeKey[datetime]:
        """Create a 'Datetime' search attribute type."""
        ...
    
    @staticmethod
    def for_keyword_list(name: str) -> SearchAttributeKey[Sequence[str]]:
        """Create a 'KeywordList' search attribute type."""
        ...
    


@dataclass(frozen=True)
class _SearchAttributeKey(SearchAttributeKey[SearchAttributeValueType]):
    _name: str
    _indexed_value_type: SearchAttributeIndexedValueType
    _value_type: Type[SearchAttributeValueType]
    @property
    def name(self) -> str:
        ...
    
    @property
    def indexed_value_type(self) -> SearchAttributeIndexedValueType:
        ...
    
    @property
    def value_type(self) -> Type[SearchAttributeValueType]:
        ...
    


class SearchAttributePair(NamedTuple, Generic[SearchAttributeValueType]):
    """A named tuple representing a key/value search attribute pair."""
    key: SearchAttributeKey[SearchAttributeValueType]
    value: SearchAttributeValueType
    ...


class SearchAttributeUpdate(ABC, Generic[SearchAttributeValueType]):
    """Representation of a search attribute update."""
    @property
    @abstractmethod
    def key(self) -> SearchAttributeKey[SearchAttributeValueType]:
        """Key that is being set."""
        ...
    
    @property
    @abstractmethod
    def value(self) -> Optional[SearchAttributeValueType]:
        """Value that is being set or ``None`` if being unset."""
        ...
    


@dataclass(frozen=True)
class _SearchAttributeUpdate(SearchAttributeUpdate[SearchAttributeValueType]):
    _key: SearchAttributeKey[SearchAttributeValueType]
    _value: Optional[SearchAttributeValueType]
    @property
    def key(self) -> SearchAttributeKey[SearchAttributeValueType]:
        ...
    
    @property
    def value(self) -> Optional[SearchAttributeValueType]:
        ...
    


@dataclass(frozen=True)
class TypedSearchAttributes(Collection[SearchAttributePair]):
    """Collection of typed search attributes.

    This is represented as an immutable collection of
    :py:class:`SearchAttributePair`. This can be created passing a sequence of
    pairs to the constructor.
    """
    search_attributes: Sequence[SearchAttributePair]
    empty: ClassVar[TypedSearchAttributes]
    def __post_init__(self): # -> None:
        """Post-init initialization."""
        ...
    
    def __len__(self) -> int:
        """Get the number of search attributes."""
        ...
    
    def __getitem__(self, key: SearchAttributeKey[SearchAttributeValueType]) -> SearchAttributeValueType:
        """Get a single search attribute value by key or fail with
        ``KeyError``.
        """
        ...
    
    def __iter__(self) -> Iterator[SearchAttributePair]:
        """Get an iterator over search attribute key/value pairs."""
        ...
    
    def __contains__(self, key: object) -> bool:
        """Check whether this search attribute contains the given key.

        This uses key equality so the key must be the same name and type.
        """
        ...
    
    @overload
    def get(self, key: SearchAttributeKey[SearchAttributeValueType]) -> Optional[SearchAttributeValueType]:
        ...
    
    @overload
    def get(self, key: SearchAttributeKey[SearchAttributeValueType], default: temporalio.types.AnyType) -> Union[SearchAttributeValueType, temporalio.types.AnyType]:
        ...
    
    def get(self, key: SearchAttributeKey[SearchAttributeValueType], default: Optional[Any] = ...) -> Any:
        """Get an attribute value for a key (or default). This is similar to
        dict.get.
        """
        ...
    
    def updated(self, *search_attributes: SearchAttributePair) -> TypedSearchAttributes:
        """Copy this collection, replacing attributes with matching key names or
        adding if key name not present.
        """
        ...
    


MetricAttributes: TypeAlias = Mapping[str, Union[str, int, float, bool]]
class MetricMeter(ABC):
    """Metric meter for recording metrics."""
    noop: ClassVar[MetricMeter]
    @abstractmethod
    def create_counter(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricCounter:
        """Create a counter metric for adding values.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Counter metric.
        """
        ...
    
    @abstractmethod
    def create_histogram(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogram:
        """Create a histogram metric for recording values.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Histogram metric.
        """
        ...
    
    @abstractmethod
    def create_histogram_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogramFloat:
        """Create a histogram metric for recording values.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Histogram metric.
        """
        ...
    
    @abstractmethod
    def create_histogram_timedelta(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogramTimedelta:
        """Create a histogram metric for recording values.

        Note, duration precision is millisecond. Also note, if "unit" is set as
        "duration", it will be converted to "ms" or "s" on the way out.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Histogram metric.
        """
        ...
    
    @abstractmethod
    def create_gauge(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricGauge:
        """Create a gauge metric for setting values.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Gauge metric.
        """
        ...
    
    @abstractmethod
    def create_gauge_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricGaugeFloat:
        """Create a gauge metric for setting values.

        Args:
            name: Name for the metric.
            description: Optional description for the metric.
            unit: Optional unit for the metric.

        Returns:
            Gauge metric.
        """
        ...
    
    @abstractmethod
    def with_additional_attributes(self, additional_attributes: MetricAttributes) -> MetricMeter:
        """Create a new metric meter with the given attributes appended to the
        current set.

        Args:
            additional_attributes: Additional attributes to append to the
                current set.

        Returns:
            New metric meter.

        Raises:
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricCommon(ABC):
    """Base for all metrics."""
    @property
    @abstractmethod
    def name(self) -> str:
        """Name for the metric."""
        ...
    
    @property
    @abstractmethod
    def description(self) -> Optional[str]:
        """Description for the metric if any."""
        ...
    
    @property
    @abstractmethod
    def unit(self) -> Optional[str]:
        """Unit for the metric if any."""
        ...
    
    @abstractmethod
    def with_additional_attributes(self, additional_attributes: MetricAttributes) -> Self:
        """Create a new metric with the given attributes appended to the
        current set.

        Args:
            additional_attributes: Additional attributes to append to the
                current set.

        Returns:
            New metric.

        Raises:
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricCounter(MetricCommon):
    """Counter metric created by a metric meter."""
    @abstractmethod
    def add(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Add a value to the counter.

        Args:
            value: A non-negative integer to add.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricHistogram(MetricCommon):
    """Histogram metric created by a metric meter."""
    @abstractmethod
    def record(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Record a value on the histogram.

        Args:
            value: A non-negative integer to record.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricHistogramFloat(MetricCommon):
    """Histogram metric created by a metric meter."""
    @abstractmethod
    def record(self, value: float, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Record a value on the histogram.

        Args:
            value: A non-negative float to record.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricHistogramTimedelta(MetricCommon):
    """Histogram metric created by a metric meter."""
    @abstractmethod
    def record(self, value: timedelta, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Record a value on the histogram.

        Note, duration precision is millisecond.

        Args:
            value: A non-negative timedelta to record.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricGauge(MetricCommon):
    """Gauge metric created by a metric meter."""
    @abstractmethod
    def set(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Set a value on the gauge.

        Args:
            value: A non-negative integer to set.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class MetricGaugeFloat(MetricCommon):
    """Gauge metric created by a metric meter."""
    @abstractmethod
    def set(self, value: float, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        """Set a value on the gauge.

        Args:
            value: A non-negative float to set.
            additional_attributes: Additional attributes to append to the
                current set.

        Raises:
            ValueError: Value is negative.
            TypeError: Attribute values are not the expected type.
        """
        ...
    


class _NoopMetricMeter(MetricMeter):
    def create_counter(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricCounter:
        ...
    
    def create_histogram(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogram:
        ...
    
    def create_histogram_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogramFloat:
        ...
    
    def create_histogram_timedelta(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricHistogramTimedelta:
        ...
    
    def create_gauge(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricGauge:
        ...
    
    def create_gauge_float(self, name: str, description: Optional[str] = ..., unit: Optional[str] = ...) -> MetricGaugeFloat:
        ...
    
    def with_additional_attributes(self, additional_attributes: MetricAttributes) -> MetricMeter:
        ...
    


class _NoopMetric(MetricCommon):
    def __init__(self, name: str, description: Optional[str], unit: Optional[str]) -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @property
    def description(self) -> Optional[str]:
        ...
    
    @property
    def unit(self) -> Optional[str]:
        ...
    
    def with_additional_attributes(self, additional_attributes: MetricAttributes) -> Self:
        ...
    


class _NoopMetricCounter(MetricCounter, _NoopMetric):
    def add(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


class _NoopMetricHistogram(MetricHistogram, _NoopMetric):
    def record(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


class _NoopMetricHistogramFloat(MetricHistogramFloat, _NoopMetric):
    def record(self, value: float, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


class _NoopMetricHistogramTimedelta(MetricHistogramTimedelta, _NoopMetric):
    def record(self, value: timedelta, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


class _NoopMetricGauge(MetricGauge, _NoopMetric):
    def set(self, value: int, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


class _NoopMetricGaugeFloat(MetricGaugeFloat, _NoopMetric):
    def set(self, value: float, additional_attributes: Optional[MetricAttributes] = ...) -> None:
        ...
    


@dataclass(frozen=True)
class Priority:
    """Priority contains metadata that controls relative ordering of task processing when tasks are
    backlogged in a queue. Initially, Priority will be used in activity and workflow task queues,
    which are typically where backlogs exist.

    Priority is (for now) attached to workflows and activities. Activities and child workflows
    inherit Priority from the workflow that created them, but may override fields when they are
    started or modified. For each field of a Priority on an activity/workflow, not present or equal
    to zero/empty string means to inherit the value from the calling workflow, or if there is no
    calling workflow, then use the default (documented on the field).

    The overall semantics of Priority are:
    1. First, consider "priority_key": lower number goes first.
    2. Then consider "fairness_key" and "fairness_weight" for fairness balancing.
    """
    priority_key: Optional[int] = ...
    fairness_key: Optional[str] = ...
    fairness_weight: Optional[float] = ...
    default: ClassVar[Priority]
    def __post_init__(self): # -> None:
        """Validates priority settings."""
        ...
    


class VersioningBehavior(IntEnum):
    """Specifies when a workflow might move from a worker of one Build Id to another.

    WARNING: Experimental API.
    """
    UNSPECIFIED = ...
    PINNED = ...
    AUTO_UPGRADE = ...


@dataclass(frozen=True)
class WorkerDeploymentVersion:
    """Represents the version of a specific worker deployment.

    WARNING: Experimental API.
    """
    deployment_name: str
    build_id: str
    def to_canonical_string(self) -> str:
        """Returns the canonical string representation of the version."""
        ...
    
    @staticmethod
    def from_canonical_string(canonical: str) -> WorkerDeploymentVersion:
        """Parse a version from a canonical string, which must be in the format
        `<deployment_name>.<build_id>`. Deployment name must not have a `.` in it.
        """
        ...
    


class VersioningOverride(ABC):
    """Represents the override of a worker's versioning behavior for a workflow execution.

    .. warning::
        Experimental API.
    """
    ...


@dataclass(frozen=True)
class PinnedVersioningOverride(VersioningOverride):
    """Workflow will be pinned to a specific deployment version.

    .. warning::
        Experimental API.
    """
    version: WorkerDeploymentVersion
    ...


@dataclass(frozen=True)
class AutoUpgradeVersioningOverride(VersioningOverride):
    """The workflow will auto-upgrade to the current deployment version on the next workflow task.

    .. warning::
        Experimental API.
    """
    ...


_arg_unset = ...
_non_user_defined_callables = ...
class HeaderCodecBehavior(IntEnum):
    """Different ways to handle header encoding"""
    NO_CODEC = ...
    CODEC = ...
    WORKFLOW_ONLY_CODEC = ...


