"""
This type stub file was generated by pyright.
"""

import temporalio.client
import temporalio.converter
import temporalio.worker
from contextlib import AbstractAsyncContextManager, asynccontextmanager
from typing import Any, AsyncIterator, Awaitable, Callable, Optional, Sequence, Type, TypeVar, Union
from temporalio.client import ClientConfig, WorkflowHistory
from temporalio.service import ConnectConfig, ServiceClient
from temporalio.worker import Replayer, ReplayerConfig, Worker, WorkerConfig, WorkflowReplayResult, WorkflowRunner

"""Plugin module for Temporal SDK.

This module provides plugin functionality that allows customization of both client
and worker behavior in the Temporal SDK through configurable parameters.
"""
T = TypeVar("T")
PluginParameter = Union[None, T, Callable[[Optional[T]], T]]
class SimplePlugin(temporalio.client.Plugin, temporalio.worker.Plugin):
    """A simple plugin definition which has a limited set of configurations but makes it easier to produce
    a plugin which needs to configure them.
    """
    def __init__(self, name: str, *, data_converter: PluginParameter[temporalio.converter.DataConverter] = ..., client_interceptors: PluginParameter[Sequence[temporalio.client.Interceptor]] = ..., activities: PluginParameter[Sequence[Callable]] = ..., nexus_service_handlers: PluginParameter[Sequence[Any]] = ..., workflows: PluginParameter[Sequence[Type]] = ..., workflow_runner: PluginParameter[WorkflowRunner] = ..., worker_interceptors: PluginParameter[Sequence[temporalio.worker.Interceptor]] = ..., workflow_failure_exception_types: PluginParameter[Sequence[Type[BaseException]]] = ..., run_context: Optional[Callable[[], AbstractAsyncContextManager[None]]] = ...) -> None:
        """Create a simple plugin with configurable parameters. Each of the parameters will be applied to any
            component for which they are applicable. All arguments are optional, and all but run_context can also
            be callables for more complex modification. See the type PluginParameter above.
            For details on each argument, see below.

        Args:
            name: The name of the plugin.
            data_converter: Data converter for serialization, or callable to customize existing one.
                Applied to the Client and Replayer.
            client_interceptors: Client interceptors to append, or callable to customize existing ones.
                Applied to the Client. Note, if the provided interceptor is also a worker.Interceptor,
                it will be added to any worker which uses that client.
            activities: Activity functions to append, or callable to customize existing ones.
                Applied to the Worker.
            nexus_service_handlers: Nexus service handlers to append, or callable to customize existing ones.
                Applied to the Worker.
            workflows: Workflow classes to append, or callable to customize existing ones.
                Applied to the Worker and Replayer.
            workflow_runner: Workflow runner, or callable to customize existing one.
                Applied to the Worker and Replayer.
            worker_interceptors: Worker interceptors to append, or callable to customize existing ones.
                Applied to the Worker and Replayer.
            workflow_failure_exception_types: Exception types for workflow failures to append,
                or callable to customize existing ones. Applied to the Worker and Replayer.
            run_context: A place to run custom code to wrap around the Worker (or Replayer) execution.
                Specifically, it's an async context manager producer. Applied to the Worker and Replayer.

        Returns:
            A configured Plugin instance.
        """
        ...
    
    def name(self) -> str:
        """See base class."""
        ...
    
    def configure_client(self, config: ClientConfig) -> ClientConfig:
        """See base class."""
        ...
    
    async def connect_service_client(self, config: ConnectConfig, next: Callable[[ConnectConfig], Awaitable[ServiceClient]]) -> temporalio.service.ServiceClient:
        """See base class."""
        ...
    
    def configure_worker(self, config: WorkerConfig) -> WorkerConfig:
        """See base class."""
        ...
    
    def configure_replayer(self, config: ReplayerConfig) -> ReplayerConfig:
        """See base class."""
        ...
    
    async def run_worker(self, worker: Worker, next: Callable[[Worker], Awaitable[None]]) -> None:
        """See base class."""
        ...
    
    @asynccontextmanager
    async def run_replayer(self, replayer: Replayer, histories: AsyncIterator[WorkflowHistory], next: Callable[[Replayer, AsyncIterator[WorkflowHistory]], AbstractAsyncContextManager[AsyncIterator[WorkflowReplayResult]],]) -> AsyncIterator[AsyncIterator[WorkflowReplayResult]]:
        """See base class."""
        ...
    


