"""
This type stub file was generated by pyright.
"""

import google.protobuf.message
import temporalio.api.common.v1
import temporalio.bridge.services_generated
import temporalio.exceptions
import temporalio.runtime
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import timedelta
from enum import IntEnum
from typing import ClassVar, Mapping, Optional, Tuple, TypeVar, Union

"""Underlying gRPC services."""
__version__ = ...
ServiceRequest = TypeVar("ServiceRequest", bound=google.protobuf.message.Message)
ServiceResponse = TypeVar("ServiceResponse", bound=google.protobuf.message.Message)
logger = ...
LOG_PROTOS = ...
@dataclass
class TLSConfig:
    """TLS configuration for connecting to Temporal server."""
    server_root_ca_cert: Optional[bytes] = ...
    domain: Optional[str] = ...
    client_cert: Optional[bytes] = ...
    client_private_key: Optional[bytes] = ...


@dataclass
class RetryConfig:
    """Retry configuration for server calls."""
    initial_interval_millis: int = ...
    randomization_factor: float = ...
    multiplier: float = ...
    max_interval_millis: int = ...
    max_elapsed_time_millis: Optional[int] = ...
    max_retries: int = ...


@dataclass(frozen=True)
class KeepAliveConfig:
    """Keep-alive configuration for client connections."""
    interval_millis: int = ...
    timeout_millis: int = ...
    default: ClassVar[KeepAliveConfig]


@dataclass(frozen=True)
class HttpConnectProxyConfig:
    """Configuration for HTTP CONNECT proxy for client connections."""
    target_host: str
    basic_auth: Optional[Tuple[str, str]] = ...


@dataclass
class ConnectConfig:
    """Config for connecting to the server."""
    target_host: str
    api_key: Optional[str] = ...
    tls: Union[bool, TLSConfig] = ...
    retry_config: Optional[RetryConfig] = ...
    keep_alive_config: Optional[KeepAliveConfig] = ...
    rpc_metadata: Mapping[str, Union[str, bytes]] = ...
    identity: str = ...
    lazy: bool = ...
    runtime: Optional[temporalio.runtime.Runtime] = ...
    http_connect_proxy_config: Optional[HttpConnectProxyConfig] = ...
    def __post_init__(self) -> None:
        """Set extra defaults on unset properties."""
        ...
    


class ServiceClient(ABC):
    """Direct client to Temporal services."""
    @staticmethod
    async def connect(config: ConnectConfig) -> ServiceClient:
        """Connect directly to Temporal services."""
        ...
    
    def __init__(self, config: ConnectConfig) -> None:
        """Initialize the base service client."""
        ...
    
    async def check_health(self, *, service: str = ..., retry: bool = ..., metadata: Mapping[str, Union[str, bytes]] = ..., timeout: Optional[timedelta] = ...) -> bool:
        """Check whether the WorkflowService is up.

        In addition to accepting which service to check health on, this accepts
        some of the same parameters as other RPC calls. See
        :py:meth:`ServiceCall.__call__`.

        Returns:
            True when available, false if the server is running but the service
            is unavailable (rare), or raises an error if server/service cannot
            be reached.
        """
        ...
    
    @property
    @abstractmethod
    def worker_service_client(self) -> _BridgeServiceClient:
        """Underlying service client."""
        ...
    
    @abstractmethod
    def update_rpc_metadata(self, metadata: Mapping[str, Union[str, bytes]]) -> None:
        """Update service client's RPC metadata."""
        ...
    
    @abstractmethod
    def update_api_key(self, api_key: Optional[str]) -> None:
        """Update service client's API key."""
        ...
    


class WorkflowService(temporalio.bridge.services_generated.WorkflowService):
    """Client to the Temporal server's workflow service."""
    ...


class OperatorService(temporalio.bridge.services_generated.OperatorService):
    """Client to the Temporal server's operator service."""
    ...


class CloudService(temporalio.bridge.services_generated.CloudService):
    """Client to the Temporal server's cloud service."""
    ...


class TestService(temporalio.bridge.services_generated.TestService):
    """Client to the Temporal test server's test service."""
    ...


class HealthService(temporalio.bridge.services_generated.HealthService):
    """Client to the Temporal server's health service."""
    ...


class _BridgeServiceClient(ServiceClient):
    @staticmethod
    async def connect(config: ConnectConfig) -> _BridgeServiceClient:
        ...
    
    def __init__(self, config: ConnectConfig) -> None:
        ...
    
    @property
    def worker_service_client(self) -> _BridgeServiceClient:
        """Underlying service client."""
        ...
    
    def update_rpc_metadata(self, metadata: Mapping[str, Union[str, bytes]]) -> None:
        """Update Core client metadata."""
        ...
    
    def update_api_key(self, api_key: Optional[str]) -> None:
        """Update Core client API key."""
        ...
    


class RPCStatusCode(IntEnum):
    """Status code for :py:class:`RPCError`."""
    OK = ...
    CANCELLED = ...
    UNKNOWN = ...
    INVALID_ARGUMENT = ...
    DEADLINE_EXCEEDED = ...
    NOT_FOUND = ...
    ALREADY_EXISTS = ...
    PERMISSION_DENIED = ...
    RESOURCE_EXHAUSTED = ...
    FAILED_PRECONDITION = ...
    ABORTED = ...
    OUT_OF_RANGE = ...
    UNIMPLEMENTED = ...
    INTERNAL = ...
    UNAVAILABLE = ...
    DATA_LOSS = ...
    UNAUTHENTICATED = ...


class RPCError(temporalio.exceptions.TemporalError):
    """Error during RPC call."""
    def __init__(self, message: str, status: RPCStatusCode, raw_grpc_status: bytes) -> None:
        """Initialize RPC error."""
        ...
    
    @property
    def message(self) -> str:
        """Message for the error."""
        ...
    
    @property
    def status(self) -> RPCStatusCode:
        """Status code for the error."""
        ...
    
    @property
    def raw_grpc_status(self) -> bytes:
        """Raw gRPC status bytes."""
        ...
    
    @property
    def grpc_status(self) -> temporalio.api.common.v1.GrpcStatus:
        """Status of the gRPC call with details."""
        ...
    


