"""
This type stub file was generated by pyright.
"""

from .message_pb2 import Account, AccountSpec, AuditLogSinkSpec, Metrics, MetricsSpec

__all__ = ["Account", "AccountSpec", "AuditLogSinkSpec", "Metrics", "MetricsSpec"]
